### ISSUE TITLE
cohttp 5.3.0: `Cookie.Set_cookie_hdr.extract` only work with lower case `set-cookie` and not uppercase `Set-Cookie`

### ISSUE THREAD

**Issue by chomosuke** [mirage/ocaml-cohttp#1007]
My work around is:
```ocaml
    let header =
      Header.add_multi header "set-cookie" @@ Header.get_multi header "Set-Cookie"
    in
```

I noticed that this has already been fixed in master with `Http.Header.Private.caseless_equal` but it'll be nice if the fix can be backported.

Thank you :)

**Comment by mseri** [comment]
Thanks. If you send a PR against the https://github.com/mirage/ocaml-cohttp/tree/v5-backports branch, I'd be happy to review it and eventually prepare a bugfix release

**Comment by mseri** [comment]
Thanks for the PR and sorry for the delay, I have submitted the release: https://github.com/ocaml/opam-repository/pull/24936
