### ISSUE TITLE
cohttp-curl swallows errors

### ISSUE THREAD

**Issue by wokalski** [mirage/ocaml-cohttp#1029]
If curl fails with what normally would be an exception on `Curl.perform`, cohttp-curl doesn't report it to the user. It gets swallowed somewhere and the response/body promises never resolve. I was not able to track it down due to the inherent complexity of the `Curl.Multi` stack.

**Comment by rgrinberg** [comment]
Do you have a repro we could look at?

**Comment by rgrinberg** [comment]
Fixed in #1056

**Comment by wokalski** [comment]
I didn't have a clean repro, sorry! I created the issue after I had deleted the code.

Thanks for fixing it!
