### ISSUE TITLE
Clean up signature land a little?

### ISSUE THREAD

**Issue by rgrinberg** [mirage/ocaml-cohttp#110]
The idea is inspired straight from what you do with mirage. Keep all the `module type` definitions in one big mli file. The benefits that i'd like to achieve are:
- Easier to browse the source code since all the signatures are in one place
- No need to copy paste the signatures in both ml and mli if you only keep it in mli (like IO.mli) for example.

Obviously much more thought has to go to handle the organization/hierarchy of the signatures and also keep the async/lwt separation. I'm just posting it here as an idea.

**Comment by yomimono** [comment]
@rgrinberg It's bug cleaning day in Mirage-land, which means I'm digging up ancient threads :) Do you think the current signature situation in cohttp is more satisfactory, or perhaps are there more specific issues we could close this out in favor of?

(Also, if you'd like me not to dig around in `cohttp` when rooting around through old issues, please say so -- I can leave this repository alone very easily!)

**Comment by rgrinberg** [comment]
Feel free to cleanup old issues. Yes, this one can be closed safely.
