### ISSUE TITLE
Empty chunk

### ISSUE THREAD

**Issue by dinosaure** [mirage/ocaml-cohttp#136]
Hello,

During my migration with ocsigenserver and cohttp when we had a chunked transfer with `Lwt_stream.t` we had some blocks that were empty (but that does not mean as long as the transfer was completed).

Thus it happened that sent cohttp `0\r\n` (which corresponds to the end of the chunk mode sent in the HTTP protocol) when we had not finished. Cohttp could very well ignore empty chunks (at least, that's what we do on our side here ocsigen/ocsigenserver@dadf5623).

I think the line to edit it [here](https://github.com/mirage/ocaml-cohttp/blob/master/cohttp/transfer_io.ml#L48).

**Comment by rgrinberg** [comment]
Fixed in master. Will be released in 0.16.0
