### ISSUE TITLE
cohttp returns nothing for bad requests

### ISSUE THREAD

**Issue by yomimono** [mirage/ocaml-cohttp#146]
cohttp seems not to return an HTTP response with an error code when an unrecognized method or HTTP version was submitted.  It neither sends any information to the client, nor does it send an RST or a FIN (although it does seem to call the conn_closed callback).

While there's code for constructing HTTP 400 and 405 messages, which is invoked in `cohttp/request.ml` on recognition of an invalid request, `cohttp_lwt.ml` seems to regard both null-content and invalid requests as equally undeserving of a response:

```
317             Request.read ic >>= function                                        
318             | `Eof | `Invalid _ -> (* TODO: request logger for invalid req *)   
319               Lwt_mutex.unlock read_m;                                          
320               return None     
```

It would greatly ease some testing that I'm doing if error responses were instead sent for invalid requests.

**Comment by rgrinberg** [comment]
Custom methods are already supported. I agree we should support handling bad requests. I suggest adding a callback to the server implementation for handling bad requests.

**Comment by yomimono** [comment]
Indeed, unsupported methods now get a nice error message:

```
$ nc 127.0.0.1 8080
UNICORN / HTTP/1.1

HTTP/1.1 405 Method Not Allowed
allow: HEAD
allow: GET
content-length: 211

<html><body><h2>Method Not Allowed</h2><p><b>UNICORN</b>is not an allowed method on <b>/</b></p><p>Allowed methods on <b>/</b> are <b>GET,HEAD</b></p><hr />Served by Cohttp/Lwt listening on :::8080</body></html>
```

but bad requests are still not quite right:

```
$ nc 127.0.0.1 8080
GET HTTP/1.1 HTTP/1.1
$
```

A connection closure is properly initiated by `cohttp-server-lwt` as of verion 1.0.2 , instead of the connection hang I reported for an earlier version (although possibly this is a difference between `cohttp-mirage` and `cohttp-server-lwt`; I unfortunately wasn't clear about which had the wrong behavior in the original report).
