### ISSUE TITLE
Remove hard dependency on camlp4

### ISSUE THREAD

**Issue by whitequark** [mirage/ocaml-cohttp#180]
The dependency stems from:

* [x] - type_conv `with sexp` and `with fields`.
* [x] - pa_lwt
* [ ] - js_of_ocaml syntax extension

**Comment by vbmithr** [comment]
This is now fixed. Js_of_ocaml depends on camlp4 but this is an optional dependency of cohttp, so there is no hard dependency on camlp4 anymore. Closing this.
