### ISSUE TITLE
Higher level HTTP response interface

### ISSUE THREAD

**Issue by avsm** [mirage/ocaml-cohttp#203]
I'm putting this towards 1.0 at the moment although it's not an API level change.

But I wanted to record this awesome diagram that could be turned into an OCaml GADT... 
http://viswaug.files.wordpress.com/2008/11/http-headers-status1.png

**Comment by seliopou** [comment]
:+1: That is the state machine that [webmachine](https://github.com/basho/webmachine) exposes to its users as an interface. Each decision node is a function that the user provides, with reasonable defaults in their absence.

I was planning on doing this anyways, so I'd be happy to help when the time comes.

**Comment by rgrinberg** [comment]
Should this really be in cohttp however? I'd much rather see people experimenting with this kind of api on top of cohttp.

**Comment by seliopou** [comment]
Yes, separating it out into another repo may be wiser than shipping it with cohttp. If I start experimenting I'll let you guys know.

**Comment by rgrinberg** [comment]
Awesome. To draw some parallels with webmachine it might make sense just to think of cohttp as cowboy/mochi. I.e. a very low level (but typed) layer to http.

**Comment by avsm** [comment]
Would love to have a higher level HTTP fetcher on the lines of webmachine...

**Comment by rgrinberg** [comment]
@seliopou has already done a great job on this in https://github.com/inhabitedtype/ocaml-webmachine

Let's focus on giving him all the tools he needs to implement this properly.

**Comment by hcarty** [comment]
Is the repository private @rgrinberg?

**Comment by rgrinberg** [comment]
Oops, yes it is. I'm not sure when it will go public but the chances of it coming out ahead of anything we might cook up in cohttp in the meantime close to 1.

**Comment by seliopou** [comment]
The repository is indeed private at the moment, though I plan to make it public shortly. Since [Inhabited Type](http://inhabitedtype.com) is organized as a for-profit entity, the name of the project will likely change upon release, so as to not have any trademark issues with Basho. The name that's currently in the lead is humphrey.

**Comment by seliopou** [comment]
I just released this today. Rather than calling it humphrey, I stuck with [webmachine](https://github.com/inhabitedtype/ocaml-webmachine).
