### ISSUE TITLE
Exception: Ssl.Read_error Ssl.Error_syscall when reading a body stream

### ISSUE THREAD

**Issue by jameister** [mirage/ocaml-cohttp#204]
I'm experiencing an issue with cohttp.0.12.0 and conduit.0.6.1. Not sure which package is responsible, since they updated at the same time, so I'll post the info here.

What happens is, for certain HTTPS calls, attempting to read the Cohttp_lwt_body.t stream from the response will block for several minutes, eventually terminating with Ssl.Read_error Ssl.Error_syscall. I don't see a full stack trace, just a reference to line 494 of lwt_unix.ml, the "action()" inside the function retry_syscall. dtruss reports that a read() call is failing with errno 35, either EAGAIN or EWOULDBLOCK (they use the same errno on OS X).

Here's what I've been able to figure out so far:
- I don't encounter this error with cohttp.0.11.2 and conduit.0.5.1.
- The request I'm making through Cohttp is a Google API call over HTTPS. In particular, it's a DELETE request. All other methods (GET, POST, etc.) are working fine with this Google API. DELETE calls made to other APIs work too.
- If I make the request with curl, it succeeds, and the response body is empty (as expected).

Unfortunately, I haven't managed to reproduce this issue outside of the Google API where I encountered it. That API requires an access token that expires every hour and must be refreshed through OAuth. So if I give you the exact request I made, it won't work anymore by the time you see it.

Any ideas? What other details can I give to help? I'm running OCaml 4.01 on Mac OS 10.9.5.

**Comment by rgrinberg** [comment]
Closing this on the basis that further progress is unlikely without more information on how to reproduce.
