### ISSUE TITLE
Test clients against bad servers

### ISSUE THREAD

**Issue by rgrinberg** [mirage/ocaml-cohttp#206]
https://github.com/kevinburke/hamms provides runnable examples of scenarios with bad servers. Would be interesting to see how our clients fare.

**Comment by marklrh** [comment]
I've done all the tests using hamms (sorry for taking so much time). I've studied pathod, which provides more comprehensive features. I guess we can use it to test any specific problems

**Comment by rgrinberg** [comment]
@marklrh do you think we can conclude this ticket now?

**Comment by marklrh** [comment]
Yes if you and Anil think there is no need to do more tests

---
Runhang Li
University of California, Los Angeles

**Comment by rgrinberg** [comment]
Well I believe we've completed the original hamms tests. They did end up catching a bug (reported elsewhere as well) but we've fixed.

My vote would be to close this and/or make some final remarks now.
