### ISSUE TITLE
Add link to http://mirage.github.io/cohttp to README

### ISSUE THREAD

**Issue by neojski** [mirage/ocaml-cohttp#237]
It's not there but it should. I didn't even realize it exists for some time.

**Comment by neojski** [comment]
And for some reason there is no Cohttp_async there.

**Comment by avsm** [comment]
It's out of date, unfortunately.  We have a new doc generator that's almost complete that lets this be rebuilt and be much prettier, with cross-references and functor-friendly.  Leaving this open until that's done.

**Comment by yomimono** [comment]
A link was added in commit 44ae06ac41de4158c7ad9c7d1e3b20103b5b57ee .
