### ISSUE TITLE
split into multiple opam packages

### ISSUE THREAD

**Issue by avsm** [mirage/ocaml-cohttp#238]
We could have virtual packages for the depopts (e.g. `cohttp-lwt`) as a shim before a more complete split.  Via @yminsky:

> I'm curious why the cohttp package works as it does.  It seems like it
> would be cleaner to break something like cohttp into three packages:
> cohttp-base, cohttp-lwt, and cohttp-async.  As it is, the rebuilding
> of cohttp when you add a new dep seems suboptimal, since it causes
> packages to be removed and re-added that aren't really required.

One annoying problem is that we can't use the OPAM 1.2 pinning workflow with multiple packages in one repository.  @AltGr @samoht, reckon it's worth making an upstream OPAM bug to think about this feature?  It would make having multiple OPAM packages in git subdirectories a lot easier.

**Comment by AltGr** [comment]
Hmm, you mean something like several packages pinned to the same repo and synchronized ? Indeed, it's possible but may quickly get tedious at the moment. Not sure exactly how to solve this though. To help share dev environments there was the idea to allow `pinning pack` files that you could set or remove in one command -- how would that relate to this ?

**Comment by samoht** [comment]
Not sure it's possible actually: if you have an opam file at the root of your repo that pretty much force you to have one opam package if you still want be able to pin I think

**Comment by avsm** [comment]
I was thinking that having the option of a directory structure instead of a direct opam file might help, so you could place multiple packages/ in there (selected by the name of the pin)

**Comment by rgrinberg** [comment]
Does this also has the caveat of having to rename all of our findlib packages? AFAIK it's not possible to have findlib sub packages (e.g. cohttp.async) across multiple META files.

Anyway, I'm +1 on having multiple opam packages from the same repo, but please let's not split the git repo.

**Comment by AltGr** [comment]
Simply allowing <name>.opam (like we already have <name>.install) on a git repo could be enough in this case. That may be a worthwile addition.

**Comment by avsm** [comment]
@AltGr  Agreed that the `.opam` suffix would be a good virtual package naming solution
@rgrinberg Also agreed on not being keen to split the packages.  I don't think we have to have multiple findlib packages, since we can use the `exists_if` predicate to install the files under a common `cohttp` findlib space from the dependent packages.

**Comment by rgrinberg** [comment]
I believe this is also necessary for #252 because I don't think .install files work with dep_exts

**Comment by samoht** [comment]
@rgrinberg yes they do. You can prefix the files by `?` to say they are optionally built. Trying to removing a non-existing `?` file will not cause an error.

**Comment by AltGr** [comment]
Latest dev opam supports file `pkg.opam` when pinning `pkg`, additionally to the more general `opam` that lets you choose any package name. It'll be in 1.2.1

**Comment by rgrinberg** [comment]
@samoht @avsm for a first cut, I can do pretty much what conduit is doing. Have sub packages that are nothing more than just `$ ocamlfind query` calls.

**Comment by yomimono** [comment]
This happened as part of the `jbuilder` conversion.  Well done, all!
