### ISSUE TITLE
IO.read should not gobble errors silently

### ISSUE THREAD

**Issue by avsm** [mirage/ocaml-cohttp#242]
IO.read currently returns an option, with no ability to comment on the sort of error it's returning.  This is a fairly big revision, but it needs to move to a model where errors and end-of-files are distinguished.

See #207

**Comment by Chris00** [comment]
What is the preferred scheme for error handling?  Using something like [Or_error](https://blogs.janestreet.com/how-to-fail-introducing-or-error-dot-t/), using `Lwt.fail` (nor really portable to async), polymorphic variants,…?

**Comment by talex5** [comment]
Currently undecided, but I'm collecting comments and proposals here: https://github.com/mirage/mirage-www/pull/274

(also, there's lots of discussion on the mailing list at present)

**Comment by avsm** [comment]
Gobbling errors like is is really, really harmful in larger scale uses of Cohttp.  Running https://github.com/avsm/opam-mirror is causing undebuggable failures when running a large number of threads.  This must be fixed before a 1.0 despite the interface breaking change I think /cc @rgrinberg

**Comment by SGrondin** [comment]
Agreed. I'm running a busy cohttp server and managing its crashes and errors is a pain.

**Comment by rgrinberg** [comment]
@avsm I'm +1231241 on this change but why do you consider this a breaking change? I don't consider `S.IO` part of our stable API.

@SGrondin Can you please describe in a bit more detail. If it's graphic enough, it would encourage me to crack my knuckles and finally tackle this.

**Comment by yomimono** [comment]
`src/s.ml` now has a `module type Http_io` with

```
val read : IO.ic -> [ `Eof | `Invalid of string | `Ok of t ] IO.t
```

 , which seems to fulfill this request, so I'll close this issue.  If this is incomplete or incorrect, please feel free to reopen.
