### ISSUE TITLE
Transfer-Encoding Header is injected into responses

### ISSUE THREAD

**Issue by SGrondin** [mirage/ocaml-cohttp#246]
Another bad case of Header injection.
This one completly breaks the application I'm trying to build.
Once again I don't know the codebase subtleties enough to fix it myself, so I debugged it for you guys as much as I could.

Basically, `Server.respond`ing with a stream will set the `Transfer-Encoding` to chunked. That makes sense, but if I already know the expected length of the stream I'd like to be able to specify the `Content-Length` myself and not have Cohttp inject the `Transfer-Encoding` header for me.

[Server.respond](https://github.com/mirage/ocaml-cohttp/blob/d0aa1cb55b364ba085384ef0fe3eaa6dce9554be/lwt/cohttp_lwt.ml#L298)
calls
[Cohttp_lwt_body.transfer_encoding](https://github.com/mirage/ocaml-cohttp/blob/86b4042c0e95f00eeeb7a02a474a3c7b8091e968/lwt/cohttp_lwt_body.ml#L87)

It would make more sense if it ONLY injected `Transfer-Encoding` if `Content-Length` is not present. In my current application, I have to manually delete `Content-Length` because it breaks `curl` and others if `Transfer-Encoding` is also present. But that also breaks other clients that did not request a Chunked response and got one (the extra control bytes for Chunked blow up everything).

Sure, I could buffer the stream and only respond with a string once I have everything, but that's ugly and horrible for performance.

Thanks for looking into it, it's probably not a huge fix and it would help me tremendously.

**Comment by talex5** [comment]
You should be able to make the response manually. I use:

    let body = Cohttp_lwt_body.of_stream data in
    let headers = Cohttp.Header.init_with "Content-Length" (Int64.to_string size) in
    let encoding = Cohttp.Transfer.Fixed size in
    let res = H.Response.make ~status:`OK ~encoding ~headers () in
    return (res, body)

**Comment by SGrondin** [comment]
Thanks @talex5 that worked. I'm not sure how I missed that feature from reading the docs. Obviously it's low priority, but I think it could be good if Server.respond didn't use Chunked mode when a length is already provided.

Nice blog, btw.

**Comment by rgrinberg** [comment]
Yes cohttp should be smarter and default to fixed if the response is provided as a string.

**Comment by avsm** [comment]
I've actually just fixed this in my proxy branch. Commit incoming

**Comment by avsm** [comment]
My fix was for requests, not responses (mirage/ocaml-cohttp#268).

Looking into the server end of things now -- `Response.read` does do the right thing on the wire by detecting transfer-encoding, content-length and range headers.  However, the same is probably not done by the construction functions.

**Comment by avsm** [comment]
Testing a fix in 05ec3ddd24e0f4da3dc281a6f8cde05f3eddfc2b

**Comment by rgrinberg** [comment]
@SGrondin I Believe we fixed all of these issues in master. Could you please confirm?

**Comment by SGrondin** [comment]
Seems to work pretty well from my limited testing. I'll probably keep setting `~chunked` manually though.

**Comment by rgrinberg** [comment]
If that option is important to you then you should definitely set it manually. We are still in the stage where we are tweaking defaults for things like this.
