### ISSUE TITLE
Proxied requests confuse the URI parser

### ISSUE THREAD

**Issue by SGrondin** [mirage/ocaml-cohttp#248]
When I set the system-wide HTTP proxy on Debian to forward all traffic to a Cohttp application, the calls come in as `GET //simongrondin.name/files/fifty.txt` instead of `GET http://simongrondin.name/files/fifty.txt`.

The URI parser gets confused and interprets them like this:
```
Uri.to_string (Request.uri req)
> http://simongrondin.namehttp//simongrondin.name/files/fifty.txt
```

**Comment by rgrinberg** [comment]
Are there any headers that come with this `GET //simongrondin.name/files/fifty.txt` request? I'm looking at   a `host` header specifically.

**Comment by SGrondin** [comment]
Host is, as expected, `Host: simongrondin.name`

**Comment by rgrinberg** [comment]
OK, so this is the culprit: https://github.com/mirage/ocaml-cohttp/blob/master/lib/request.ml#L97

**Comment by SGrondin** [comment]
By the way it's easier to reproduce by setting the Firefox HTTP proxy setting to a local cohttp server.

**Comment by dsheets** [comment]
@rgrinberg are you on this? It looks like <https://github.com/mirage/ocaml-cohttp/commit/d04701fa4ae1161eec148ad5871647ef08109bc1#diff-daa4e580cf195143c70372b6183a5a40R140> should really be using  proper `Uri` functional updates rather than string concatenation (will handle relative paths correctly).  Also, I'd recommend switching to a scheme-relative identifiers.

**Comment by SGrondin** [comment]
This is the absolutely horrible hack I'm using for now, but it works until a fix is (hopefully) released in 0.16, in case anyone googled and finds this issue.

```ocaml
let fix_uri uri =
	let ungarble uri host protocol_len =
		uri
		|> fun uri -> ((Uri.with_host uri (Some (String.slice host 0 (-protocol_len)))), (String.length host - protocol_len))
		|> fun (uri, len) -> Uri.with_path uri (String.slice (Uri.path uri) (len + 2) 0)
	in
	match (uri |> Uri.host |> Option.value ~default:"") with
	| host when String.is_suffix ~suffix:"http" host -> ungarble uri host 4
	| host when String.is_suffix ~suffix:"https" host -> ungarble uri host 5
	| host when (((String.length host) / 2) mod 2 = 0) && ((String.slice host (String.length host / 2) 0) = (String.slice host 0 (String.length host / 2))) ->
			Uri.with_host uri (Some (String.slice host 0 (String.length host / 2)))
	| _ -> uri

```

**Comment by avsm** [comment]
I stuck a functional update fix into avsm/ocaml-cohttp@0260455999e9f29e64e6de3b89d302ac036a60e5, but uri is doing some odd things:

```
#require "uri.top"
Uri.with_port (Uri.of_string "/") None ;;
- : Uri.t = ///
Uri.of_string "/" ;;
- : Uri.t = /
```
Those should really be equivalent.

**Comment by avsm** [comment]
See mirage/ocaml-uri#63

**Comment by SGrondin** [comment]
This is still happening even with Uri 1.8.0.

`http://en.wikipedia.orghttp//en.wikipedia.org/wiki/GNU_C_Library`

**Comment by rgrinberg** [comment]
@SGrondin I assume using cohttp master as well?

**Comment by SGrondin** [comment]
`0.15.2`

Oh, I didn't see it was closed in 37bcbd8. For some reason I thought it was in Uri 1.8.0.

**Comment by SGrondin** [comment]
I just tested it against master and it's still happening.

`Uri.to_string target` -> `"http://en.wikipedia.orghttp//en.wikipedia.org/favicon.ico"`

**Comment by rgrinberg** [comment]
@SGrondin So i assume the request looks something like this then:

```
GET http//en.wikipedia.org/favicon.ico
Host: http://en.wikipedia.org
```

**Comment by SGrondin** [comment]
Try it by setting your Firefox (or system) proxy to a cohttp server and then try to browse wikipedia.org in a browser. http://i.imgur.com/81vdpWS.png

**Comment by avsm** [comment]
I cna't reproduce this, but I'm seeing some suspicious activity in `cohttp-proxy-lwt` I'm investigating.

When browsing wikipedia, 400 Bad Requests show up, which they really shouldn't.  Probably some hop-by-hop heading that isn't being handled right.

```
{65171} <<< X-Varnish: 2305557189 2305557059, 2102571268 2102571170, 758309883 757593122
{65171} <<< Via: 1.1 varnish, 1.1 varnish, 1.1 varnish
{65171} <<< Date: Mon, 23 Mar 2015 11:47:20 GMT
{65171} <<< Age: 924
{65171} <<< Connection: keep-alive
{65171} <<< X-Cache: cp1055 hit (7), amssq31 hit (22), amssq37 frontend hit (4789)
{65171} <<< Cache-Control: private, s-maxage=0, max-age=0, must-revalidate
{65171} <<< 
{65171} >>> HTTP/1.1 304 Not Modified
{65171} >>> age: 924
{65171} >>> cache-control: private, s-maxage=0, max-age=0, must-revalidate
{65171} >>> content-language: en
{65171} >>> content-type: text/html; charset=UTF-8
{65171} >>> date: Mon, 23 Mar 2015 11:47:20 GMT
{65171} >>> last-modified: Mon, 23 Mar 2015 11:31:56 GMT
{65171} >>> server: Apache
{65171} >>> transfer-encoding: chunked
{65171} >>> vary: Accept-Encoding,Cookie
{65171} >>> via: 1.1 varnish, 1.1 varnish, 1.1 varnish
{65171} >>> x-analytics: page_id=15580374;ns=0
{65171} >>> x-cache: cp1055 hit (7), amssq31 hit (22), amssq37 frontend hit (4789)
{65171} >>> x-content-type-options: nosniff
{65171} >>> x-powered-by: HHVM/3.3.1
{65171} >>> x-ua-compatible: IE=Edge
{65171} >>> x-varnish: 2305557189 2305557059, 2102571268 2102571170, 758309883 757593122
{65171} >>> 
{65171} <<<[4096] HTTP/1.1 400 Bad Request

{65171} >>> 1c
{65171} >>> HTTP/1.1 400 Bad Request

{65171} >>> 
{65171} <<<[4096] {65171} >>> 0
```

**Comment by avsm** [comment]
That debug output shows the browser writing a request, it being rewritten correctly for upstream (with the URL rewritten to make it a relative URL).

The problem appears immediately afterwards when a HTTP bad request shows up.  This is possibly related to pipelining behaviour.

**Comment by SGrondin** [comment]
As requested, here's a [small test proxy](https://gist.github.com/SGrondin/8885e5cc96a16b3ca21d) that demonstrates the bug.

Set your system proxy to `127.0.0.1:15000` or [set your Firefox HTTP proxy to the same](https://i.imgur.com/81vdpWS.png).

As you try to browse HTTP sites, you'll see in the console that the hostname for the incoming requests is broken and nothing can be fetched. Then edit line 25 to uncomment the call to `fix_uri`, recompile and restart the server and you'll see that browsing is fine.

Compile with `corebuild -tag debug -pkg lwt -pkg cohttp.lwt main.native` or `ocamlfind ocamlc -c main.ml -thread -package core,cohttp.lwt`.

**Comment by marklrh** [comment]
Without ``fix_uri`` being uncommented:
![img](http://i.imgur.com/uyZv55n.png)

I cannot reproduce it. Has this bug already been fixed?

**Comment by SGrondin** [comment]
Indeed, some unrelated change in 0.16.0 fixed it. Nice

**Comment by dsheets** [comment]
This was a pretty severe issue. It would be nice to know which commit fixed the issue so we can understand the cause of the original defect.
