### ISSUE TITLE
Tutorial walkthrough of cohttp

### ISSUE THREAD

**Issue by mk270** [mirage/ocaml-cohttp#25]

**Comment by rgrinberg** [comment]
@avsm Is this issue still necessary? If so could you describe it a little bit better so that someone else can tackle it.

**Comment by avsm** [comment]
One library I really admire is the `wreq` Haskell HTTP client library.  I was thinking that a walkthrough similar to  http://www.serpentine.com/wreq/tutorial.html would be the ideal set of code snippets for most users of Cohttp as a client.  A server side one could similarly have just enough to point people to (e.g.) opium or other web frameworks.

**Comment by rgrinberg** [comment]
@mk270 I've recently updated the front page readme with some docs. Feedback is welcome.
