### ISSUE TITLE
Provide Location header helper

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-cohttp#253]
Location is a common header for handling redirects and similar functionality. See <https://github.com/samoht/ocaml-git/commit/dd675f52335bf019a4c19b718979e2a3e48e3e74#diff-3df45e5a85ed8f1ae4d796d2c71eebaaR146> for motivation.

**Comment by rgrinberg** [comment]
I suppose what you head mean is something like

```ocaml
val location : Header.t -> Uri.t option
```

Apart from that, we can add redirection as a feature for the http clients.

**Comment by dsheets** [comment]
I mean something like that.

I'm generally wary of adding redirection support at this layer because many clients will want more information about the redirect chain.

I think a more fully featured client library should be built on top of this and called something like "courl". It would also handle schemes other than http.

**Comment by rgrinberg** [comment]
Makes sense. The basic clients are currently created in such a way that it's hard to reuse this logic anyway.

Have a look at #254

**Comment by dsheets** [comment]
:+1:

**Comment by rgrinberg** [comment]
Fixed.
