### ISSUE TITLE
Will respond_file use magic-mime ?

### ISSUE THREAD

**Issue by zoggy** [mirage/ocaml-cohttp#260]
Hello,

Do you have plans to make respond_file add a mime-type in the response header (for example using magic-mime ? :-) )

**Comment by avsm** [comment]
Yep, that is sensible.  It didn't make it into 0.15.2, but I'll put that into a point release shortly.

**Comment by dsheets** [comment]
Slightly off-topic but it seems that magic-mime should actually be named something like "mime-ext-db" and the "magic" component should be reserved for the actually magical function like Unix `file(1)`.
