### ISSUE TITLE
HTTP/2

### ISSUE THREAD

**Issue by SGrondin** [mirage/ocaml-cohttp#272]
HTTP/2 was finalized recently: https://http2.github.io/

It includes, connection reuse, header compression, binary flags and other optimizations. Are there any plans to support it in 1.0? It's already supported by all the major browsers and very soon will be by all the major servers (nginx, apache, etc) as well. While probably not a huge priority for cohttp, I'm curious about where it sits on your roadmap.

Thanks.

**Comment by rgrinberg** [comment]
It's on the roadmap but definitely not for 1.0. Definitely one of the most interesting things to look at for 2.0 though.

**Comment by marklrh** [comment]
some good resource: https://github.com/bagder/http2-explained

**Comment by shinzui** [comment]
I wonder what is the status of HTTP2 support

**Comment by avsm** [comment]
None yet, but it's on my list to look at in March along with QUIC.

**Comment by ShalokShalom** [comment]
It can help with a implementation of gRPC

**Comment by ehiggs** [comment]
What's the status of HTTP2 support?

**Comment by rgrinberg** [comment]
There's https://github.com/anmonteiro/ocaml-h2 already and it wouldn't make sense for us to duplicate all that effort. Moreover, HTTP/2's uptake has been rather lackluster and it is likely going to be quickly replaced by HTTP/3. Let's re-evaluate once HTTP/3 is out.
