### ISSUE TITLE
Cohttp_async.Server using SSL Leaks Pipes

### ISSUE THREAD

**Issue by trevorsummerssmith** [mirage/ocaml-cohttp#287]
I discovered this in a program I was writing for work today, checked with a few small examples and could always reproduce it. For every handled request there are a couple of leaked pipes.

To reproduce:
1. create the cohttp_server_async example
2. Run this example with a cert and key, eg .```/cohttp_server_async.native -cert-file CERT_FILE -key-file KEY_FILE -p 9999```
3. ```ps aux | grep cohttp_server_async # get proc id```
4. ```lsof -p $PROC_ID # Note open pipes```
5. ```curl -k https://localhost:9999```
6. ```lsof -p $PROC_ID # Watch open pipes grow in number.```
7. Repeat steps 5 and 6.

Doing this same thing without ssl does *not* leak pipes.

I tracked this down to an issue with Conduit. I created a patch that fixes this issue in Conduit and fixes the above issue. However I am creating this ticket here because 1) I don't know either of these codebases that well so my fix could have unintended consequences and 2) this is an issue with cohttp.

I'll link to the Conduit pull request and ticket in a moment when I make them.

**Comment by trevorsummerssmith** [comment]
Conduit issue: https://github.com/mirage/ocaml-conduit/issues/53 (which references the pull request)

**Comment by avsm** [comment]
Good catch, thanks.  The Async backend needs a test case like the Lwt one to catch these in the future; I'll do that when reviewing.

**Comment by trevorsummerssmith** [comment]
Ping. I'm still seeing this fix this issue with further testing. Could someone more familiar with the codebase give their opinion -- it would be nice to have verification. Thanks!

**Comment by avsm** [comment]
This one should be fixed in 0.17.0 now and I don't spot it with a stress test on Async_ssl.  Could you confirm this?

**Comment by trevorsummerssmith** [comment]
The leak looks to be fixed by conduit 0.8.1. Opam will pull this in by default. However, it seems that to close this ticket the cohttp opam dependency should be updated to 0.8.1. Right now it is >= 0.7.0. Thoughts?

**Comment by rgrinberg** [comment]
@trevorsummerssmith I don't think we should update the constraints. Newer versions of cohttp are compatible with the older (and buggy) version of conduit. This is all the constraints are meant to imply.

**Comment by trevorsummerssmith** [comment]
I see, I did not know that that was the implication.

I'm personally fine with whatever sounds good to you both. It seems like there should be something documented for posterity, as this is a pretty severe bug, but perhaps this ticket is just that thing. Anyway, thanks for following up and getting this closed.

**Comment by avsm** [comment]
Constraints are usually just for build issues indeed.  In general, users are expected to form their own view on a stable version set for their particular application.  We *could* put a `messages` warning into the affected version of Cohttp though...

**Comment by trevorsummerssmith** [comment]
Hmmm..... what about a generic messages message about how to find open issues for a version? Open bugs could then be tagged in github with a version so that there would be a straightforward query to find all open issues?

**Comment by rgrinberg** [comment]
@trevorsummerssmith Let's revisit this problem once we release 1.0

I'm definitely for the idea but we must find a non-intrusive way to accomplish this project management.

**Comment by rgrinberg** [comment]
Closing the issue since the underlying bug is fixed. Thanks again Trevor.
