### ISSUE TITLE
(0.15.2) linking problems caused by some sub-libraries peeking inside the packed module

### ISSUE THREAD

**Issue by djs55** [mirage/ocaml-cohttp#299]
I had a problem building an RPM from 0.15.2. The RPM build process uses `ocamlobjinfo` to figure out which interfaces are imported by the libraries and embeds the CRCs in the package as dependencies. In 2 places in 0.15.2, sub libraries were depending on modules *within* the main cohttp pack (e.g. `Accept_types` `Transfer`) directly, rather than on the packed module itself. The result was that my RPM exposed the packed module CRCs (as expected and desired), but still depended on the inner module CRCs, so I couldn't install it.

I've worked around the problem with the following patch:
```
diff -ur ocaml-cohttp-0.15.2.a/async/cohttp_async.ml ocaml-cohttp-0.15.2.b/async/cohttp_async.ml
--- ocaml-cohttp-0.15.2.a/async/cohttp_async.ml 2015-04-03 09:24:22.222151568 +0000
+++ ocaml-cohttp-0.15.2.b/async/cohttp_async.ml 2015-04-03 09:37:35.598642885 +0000
@@ -17,6 +17,7 @@

 open Core.Std
 open Async.Std
+open Cohttp (* avoid refering to modules within the pack by mistake *)

 module IO = Cohttp_async_io

diff -ur ocaml-cohttp-0.15.2.a/lwt/string_io_lwt.mli ocaml-cohttp-0.15.2.b/lwt/string_io_lwt.mli
--- ocaml-cohttp-0.15.2.a/lwt/string_io_lwt.mli 2015-04-03 09:24:22.230155955 +0000
+++ ocaml-cohttp-0.15.2.b/lwt/string_io_lwt.mli 2015-04-03 09:30:51.157523040 +0000
@@ -22,7 +22,7 @@
    data into a {!Buffer.t}.  Never actually blocks despite the Lwt
    use, although a future revision may yield when parsing large
    strings. *)
-include S.IO
+include Cohttp.S.IO
   with type 'a t = 'a Lwt.t
   and type ic = Cohttp.String_io.buf
   and type oc = Buffer.t
```
I've not had time (yet) to try the master branch, but I thought I'd leave this here as a placeholder.

It's unfortunate that this kind of inner reference isn't precluded by the build tools, say by not adding the inner modules to the search path while building the sub-libraries.

**Comment by rgrinberg** [comment]
I've applied your patch. We'll re-open or re-create this issue if it appears again.

**Comment by djs55** [comment]
Thanks!

On Sat, Apr 4, 2015 at 5:36 PM, Rudi Grinberg <notifications@github.com>
wrote:

> I've applied your patch. We'll re-open or re-create this issue if it
> appears again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirage/ocaml-cohttp/issues/299#issuecomment-89611564>.
>



-- 
Dave Scott
