### ISSUE TITLE
More robust handling of paths beginning with //

### ISSUE THREAD

**Issue by zoggy** [mirage/ocaml-cohttp#308]
Hello,

When an uri such as `http://localhost//foo/bar` is requested, `Uri.of_string` is used on the requested path, i.e. `//foo/bar`, which returns an uri with path `/bar`, because it handles the whole string as a uri. This should be parsed as a path, to handle "incorrect" paths beginning with "//".

The call to `Uri.of_string` is here: https://github.com/mirage/ocaml-cohttp/blob/master/lib/request.ml#L113

**Comment by dsheets** [comment]
Indeed you are correct. I am preparing a patch now.

**Comment by dsheets** [comment]
#309 fixes this issue. When that PR is merged, this issue will close. Thanks for reporting the problem!

**Comment by zoggy** [comment]
The fix does not seem to handle query params correctly, i.e. with the following url:
````
http://localhost/test/?formula=foo
````
the path obtained with `Uri.path` is `/test%3Fformula=foo` instead of "/test".

**Comment by dsheets** [comment]
Indeed. :-( Sorry about that. It's the same problem as <https://github.com/mirage/irmin/pull/187#issuecomment-92703466>.

**Comment by zoggy** [comment]
I'm trying to fix it.

**Comment by zoggy** [comment]
Here is a PR: https://github.com/mirage/ocaml-cohttp/pull/317
"make test" was OK and it seems to fix my problem.
