### ISSUE TITLE
cohttp HEAD shouldn't use chunked mode

### ISSUE THREAD

**Issue by edwintorok** [mirage/ocaml-cohttp#313]
When you ask cohttp (0.16.0) to send a HEAD request by default it also sends a '0' as the body which confuses servers as they send back 400 reply with a body after the real reply.

Also if you call Cohttp_lwt_body.to_string on a HEAD request it just blocks indefinetely. Its probably ok to allow to check the length of the body for a HEAD (it might be as Content-Length in the headers) but it should probably raise an exception if you actually try to read the body of a HEAD reply.

[there are some broken servers though that do send a body for a HEAD, like some old version of nginx with gzip enabled: it sends the gzip/zlib headers in the body of the reply, that uncompresses to 0 bytes, not sure if it'd be worth supporting that]

```sh
$ cohttp-curl-lwt http://example.com -X HEAD
HTTP/1.0 400 Bad Request
Content-Type: text/html
Content-Length: 349
Connection: close
Date: Mon, 13 Apr 2015 16:07:05 GMT
Server: ECSF (ewr/15DC)

<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<title>400 - Bad Request</title>
	</head>
	<body>
		<h1>400 - Bad Request</h1>
	</body>
</html>
```

**Comment by dsheets** [comment]
I have a patchset which fixes this issue but I must sleep. I'll PR tomorrow morning (UTC).

**Comment by dsheets** [comment]
Sorry for the delay, some other issues came up that needed to be dealt with before addressing this one.

I've corrected this issue in a730637 and c5f8f37. If you could check that #321 addresses this problem, it would be appreciated.

**Comment by edwintorok** [comment]
for some reason I didn't get the github notification email (apparently smtp server died), will test this as soon as I can, probably tomorrow. thanks for the update.

**Comment by edwintorok** [comment]
looks good
