### ISSUE TITLE
HEAD request file descriptor leak (waiting for body that never arrives)

### ISSUE THREAD

**Issue by edwintorok** [mirage/ocaml-cohttp#315]
When not using chunked requests (see https://github.com/mirage/ocaml-cohttp/issues/313) HEAD requests work, but the body is still created and it leaks a file descriptor.
I cannot use Cohttp_lwt_unix.drain_body because that would block indefinetely, and I don't see other functions to forcibly close the connection either.

**Comment by dsheets** [comment]
I believe my patch for #313 will also address this.

**Comment by dsheets** [comment]
I believe this issue was fixed in c5f8f37. I tested the fix by examing `/proc/[pid]/fds` during a long sleep I inserted after reading the response header but before touching the body. For `GET` requests, a socket remains open during this time as fd 4 in cohttp_lwt_curl. For `HEAD` requests, no socket remains open. If you could confirm that #321 addresses the incorrect behavior you observed previously, we would appreciate it.

Thanks for your reports!

**Comment by edwintorok** [comment]
There are still some leaks in conduit (see https://github.com/mirage/ocaml-conduit/pull/56) but once I fixed that I don't see any more leaks with HEAD during normal usage and your `dsheets/broken-head` branch.
I'm still a little worried on what would happen if the connection is reset during reading the headers, or anywhere before the code reaches the place where it either closes the socket or sets up the GC finalizer. Also the close itself seems to be run async, so under high load I'm worried that the close would come too late even in an otherwise well behaved scenario (no errors, close called for each request).

Would it be possible to make this more robust at the API level by providing a `with_call`/`with_callv` function that makes the call, applies my `[f]` function, and does everything needed to ensure that when `with_call` returns all sockets it used are closed, even if the connection itself, reading the reply headers/body, applying my f, or anything raises an exception?

**Comment by dsheets** [comment]
Great! Your proposal definitely sounds like a good idea. I've created #323 to track that work. This issue will automatically close when `broken-head` is merged. Thanks!
