### ISSUE TITLE
Hanging whenever having an empty body in Response

### ISSUE THREAD

**Issue by fxfactorial** [mirage/ocaml-cohttp#339]
I'm encountering an issue where using, 0.17.1, `Cohttp_async.Body` on responses that have an empty body always just hangs indefinitely. 

I put some print statements in to_string around lines 101 of cohttp_async.ml but they don't even get executed, so I suppose the issue is happening even before that.

**Comment by rgrinberg** [comment]
Is it possible to post a small example to reproduce this?

**Comment by fxfactorial** [comment]
#require "core, async, cohttp, cohttp.async"

open Core.Std
open Async.Std
open Cohttp_async

let run () =
  let this_request = Request.make ~meth:`HEAD
                                  (Uri.of_string "http://localhost:8080") in
  Client.request this_request >>= fun (resp, body) ->
  Body.to_string body >>= fun b ->
  return (print_endline ("Should be empty: " ^ b))

let () =
  run ();
  never_returns (Scheduler.go ())

**Comment by rgrinberg** [comment]
@dsheets isn't this the same problem you've already solved for lwt?

**Comment by fxfactorial** [comment]
If someone can suggest me where to look, I could take a stab at it.

**Comment by rgrinberg** [comment]
@fxfactorial My previous comment referred to #321 and #322 you could refer to these to gain some insight. I haven't looked closely at this yet.

**Comment by marklrh** [comment]
The reason is that this [``Pipe.iter``](https://github.com/mirage/ocaml-cohttp/blob/master/async/cohttp_async.ml#L260) does not return.

**Comment by rgrinberg** [comment]
@marklrh could you elaborate?

From a first glance, the problem seems to occur by the server responding with a content-length > 0 and the client expecting a body to be returned.

You can observe this with:

```
$ ./cohttp_curl_lwt.native -X HEAD 'http://0.0.0.0:8080' -v # works
$ /cohttp_curl_async.native -X HEAD 'http://0.0.0.0:8080' # doesn't work
```

**Comment by marklrh** [comment]
@rgrinberg I guess maybe we are talking about the same thing. If your assumption is correct, this means that client is expecting something from the server but server does not actually send a body. The client will hang, which means that server cannot see anything from the pipe.

**Comment by marklrh** [comment]
@rgrinberg 

I added a line after [L270](https://github.com/mirage/ocaml-cohttp/blob/master/async/cohttp_async.ml#L270)
````OCaml
print_endline (Sexp.to_string (Response.sexp_of_t res));
````

The output on the terminal is 
````OCaml
((encoding(Fixed 3419))(headers((connection keep-alive)))(version HTTP_1_1)(status OK)(flush true))
````

So, the server does not actually anything about ``content-length``?

**Comment by marklrh** [comment]
@rgrinberg 

Then, at [L177](https://github.com/mirage/ocaml-cohttp/blob/master/async/cohttp_async.ml#L177), client now has a pipe. However, if it wants to read something out of it, it just hangs there, since server does not send anything?

**Comment by marklrh** [comment]
um i see why. I am making a patch

**Comment by fxfactorial** [comment]
@marklrh  Wait a second, the example was just for Head, but this should work for any method, not just head.

**Comment by rgrinberg** [comment]
@fxfactorial `$ ./cohttp_curl_async.native -X GET 'http://0.0.0.0:8080'` works well for me

**Comment by marklrh** [comment]
Here are some tests. I also tried a popular alternative of curl, which is [httpie](https://github.com/jakubroztocil/httpie)

* ``./cohttp_server_lwt.native``

  **Hang**

  * ``curl -i -X HEAD http://localhost:8080``

  **Terminate**

  * ``./cohttp_curl_lwt.native -X HEAD 'http://0.0.0.0:8080'``

  * ``./cohttp_curl_async.native -X HEAD 'http://0.0.0.0:8080'``

  * ``http HEAD 0.0.0.0:8080``

* ``./cohttp_server_async.native``

  **Hang**

  * ``curl -i -X HEAD http://localhost:8080``

  * ``./cohttp_curl_async.native -X HEAD 'http://0.0.0.0:8080'``

  **Terminate**

  * ``./cohttp_curl_lwt.native -X HEAD 'http://0.0.0.0:8080'``

  * ``http HEAD 0.0.0.0:8080``
