### ISSUE TITLE
Problems with Lwt's callv

### ISSUE THREAD

**Issue by rgrinberg** [mirage/ocaml-cohttp#347]
(This is most directly at @dsheets)

1. The main problem with callv is that it waits for all the requests to be written before attempting to process the responses.

2. I'm not sure about this point (would like confirmation). I think that you cannot add more requests after processing some responses. E.g. callv supports only the following mode of operation

```
open connection -> request -> request -> response -> response -> close connection
```

We'd like to support usage like

```
open connection -> request -> response -> request -> request -> response -> response -> close connection
```

I think that my proposed implementation of for async callv (#344) gets around these problems by doing the reads independently from the writes.

**Comment by edwintorok** [comment]
1. could be solved by using `Lwt_stream.map_s`, maybe [like this](https://github.com/mirage/ocaml-cohttp/commit/ae60dcdb55de8ba762552b25d4c954b3ea957876) (untested) and might help with 2. also.
I actually intend to use `callv` to implement persistent connections, and a callback/Lwt.task+wakeup approach might be  better than a stream, but that can be done on top of `callv`

**Comment by rgrinberg** [comment]
This particular problem was fixed by @edwintorok
