### ISSUE TITLE
Async client does not return the whole of a webpage's text.

### ISSUE THREAD

**Issue by vbmithr** [mirage/ocaml-cohttp#357]
```ocaml
open Core.Std
open Async.Std
open Cohttp_async

let main () =
  Client.get (Uri.of_string Sys.argv.(1)) >>= fun (r, b) ->
  Body.to_string b >>= fun s ->
  Printf.printf "%s\n%!" s;
  Shutdown.shutdown 0;
  Deferred.unit

let _ =
  don't_wait_for @@ main ();
  never_returns @@ Scheduler.go ()
```

Try this on `https://api.bitfinex.com/v1/trades/BTCUSD`

**Comment by rgrinberg** [comment]
You can also reproduce this with `$ ./cohttp_curl_async.native 'https://api.bitfinex.com/v1/trades/BTCUSD'

**Comment by vbmithr** [comment]
Cool, thanks for the tip. But what about the bug :p

**Comment by rgrinberg** [comment]
Seems like async's chunked encoding reader is buggy since `$ ./cohttp_curl_lwt.native` works`

**Comment by vbmithr** [comment]
Yeah, I'm looking at this now.

**Comment by vbmithr** [comment]
Works on 0.17.0, broken on 0.17.1, I'll soon figure out.

**Comment by rgrinberg** [comment]
@vbmithr Awesome, thanks.

**Comment by rgrinberg** [comment]
The only thing that's suspicious here is @artemkin 's commit

https://github.com/mirage/ocaml-cohttp/compare/v0.17.0...v0.17.1

**Comment by vbmithr** [comment]
On 29/05/2015 17:07, Rudi Grinberg wrote:
> The only thing that's suspicious here is @artemkin
> <https://github.com/artemkin> 's commit
> 
> v0.17.0...v0.17.1
> <https://github.com/mirage/ocaml-cohttp/compare/v0.17.0...v0.17.1>
> 

The semantic of those functions are wrong, anyway. `len` is not respected.

-- 
Vincent

**Comment by rgrinberg** [comment]
Yes that's a good point. I actually wonder if we should just remove that commit after https://github.com/mirage/ocaml-cohttp/pull/353 was done. It seems unnecessary.

**Comment by vbmithr** [comment]
Reverted. And we need a new release for this :)

**Comment by rgrinberg** [comment]
That's a little too fast...

I'd like to write a test for this first.

**Comment by rgrinberg** [comment]
Also, are we sure there isn't a performance regression with respect to @artemkin 's original issue?

**Comment by vbmithr** [comment]
Maybe, but a a slow program is superior to an incorrect program. And Since you commited #353 I believe, as you said, that it fixes performance issues.
But agreed I have been a bit fast on this, sorry :)

**Comment by rgrinberg** [comment]
@vbmithr I agree. But I think we should be a little more careful about this. I'm thinking if we should raise on read_exactly if the size requested is past some maximum. It's never correct for cohttp to allocate such a massive buffer.

**Comment by rgrinberg** [comment]
#359 fixes this
