### ISSUE TITLE
RFC: Manual packing and core like Std module

### ISSUE THREAD

**Issue by rgrinberg** [mirage/ocaml-cohttp#366]
I'd like to make some improvements to the module organization of cohttp.

Action plan:
- Make sure that every module is prefixed with `Cohttp_`
- Create `Cohttp_async.Std`, `Cohttp_lwt.Std` `Cohttp_xhr.Std` modules that are expected to be open to use cohttp. All backend independent bits that are part of the API will also be available under `Cohttp.`. mirage-http may follow suit with `Cohttp_mirage.Std` but that's not my call.
- Create necessary aliases not to break any compatibility.
- Create convenient aliases for stuff like `Cohttp_lwt_body` inside the various `Std` submodules.

@samoht @avsm @dsheets thoughts?

**Comment by avsm** [comment]
I'd generally be in favour of removing pack and creating explicit modules instead.  Would this be a good time to make Cohttp an OCaml 4.02 library only, and use module aliases?  We could just do this namespace rearrangement and preserve 4.01 compatibility, and then shift a later version to use the more efficient module aliases later instead.

It would be nice to have a Cohttp 1.0 that works with OCaml 4.01 just for the longer term support, as that's included in Ubuntu.

-anil

**Comment by rgrinberg** [comment]
Agreed. This change is not meant to affect backwards compatibility in any way.

> It would be nice to have a Cohttp 1.0 that works with OCaml 4.01 just for the longer term support, as that's included in Ubuntu.

Maybe ppx will be enough of a motivation for us to finally cut 1.0

**Comment by samoht** [comment]
I'm in favour of that change, and I think we should use that as a good excuse to properly document the public library (in `cohttp.mli`).

**Comment by rgrinberg** [comment]
@samoht I think that's a great idea and would make the lib a lot more approachable. But I would really hate to duplicate all module signatures `cohttp_*.mli` in `cohttp.mli`.

Is there a better way?

**Comment by rgrinberg** [comment]
This issue is resolved.
