### ISSUE TITLE
SNI is not sent when using OpenSSL

### ISSUE THREAD

**Issue by SGrondin** [mirage/ocaml-cohttp#378]
UPDATE:

This issue used to be 2 different problems. Now it's only about SNI not being sent in requests done with OpenSSL. SNI is sent with the native stack.

---

SNI (Server Name Identification) is a TLS 'extension'. It is part of the Client Hello part of the TLS handshake. It sends in clear text the hostname part of the request URI. This allows a server serving multiple HTTPS sites on a single IP to know which certificate to send to the client.

CoHTTP does not send SNI. I confirmed this behavior using the openssl CLI client, and a few other tools. [Here's the Hello in Wireshark](http://simongrondin.name/files/sni.png), notice that SNI isn't part of the Extensions.

I've confirmed the behavior using both `OpenSSL as well as `TLS.

This issue breaks every site using the free Cloudflare SSL. `mockbin.com` and `www.ahmadnassri.com` are sites that can be used for testing and debugging this issue.

I wasn't sure wheter to post this here or in mirage/ocaml-conduit, I hope this is the right place.

Thanks!

edit: It works when using ocaml-tls. But unfortunately even with the native stack there's no way to connect directly to an IP and have the SNI be some other hostname.

**Comment by avsm** [comment]
@hannesm -- is there a TLS API for SNI? This needs to be plumbed through to Conduit.

**Comment by hannesm** [comment]
SNI from the client side is [sent](https://github.com/mirleft/ocaml-tls/blob/39523d31892ff0d07960114c28129ae167eae9b0/lib/handshake_client.ml#L13-L16) when `config.peer_name` is `Some host` (which is done in [client_of_fd](https://github.com/mirleft/ocaml-tls/blob/39523d31892ff0d07960114c28129ae167eae9b0/lwt/tls_lwt.ml#L184-L186), used by [ocaml-conduit](https://github.com/mirage/ocaml-conduit/blob/master/lib/conduit_lwt_tls.ml#L40)).

@SGrondin your wireshark screenshot is from conduit using OpenSSL, could you paste one which uses native OCaml-TLS?

**Comment by SGrondin** [comment]
Here it is with the native stack: http://simongrondin.name/files/sni2.png

So SNI **is** sent with the native stack, but it's not with OpenSSL. Sorry for the confusion.

The reason I'm directly connecting to an IP is that I resolve the hostname elsewhere and do manipulations on it. I `Client.call` an IP instead of the hostname because I don't want CoHTTP to try to resolve it, but I'd like the connection to use the hostname anyway... I'm not sure how to achieve that.

**Comment by SGrondin** [comment]
#390 takes care of half of the problem here, so I'm renaming this issue to better reflect the other half of the problem. The native stack sends the SNI, but OpenSSL doesn't.

**Comment by pdonadeo** [comment]
Same problem here. I spent last night debugging and I didn't understand where to submit a patch, I'm using Cohttp_async so three packages are involved: cohttp,  conduit and async_ssl.

I writing a simple HTTP client and some servers simply drop the connection if SNI is not sent by the client. Any suggestion about how to start to solve this issue? Not even sure this is the right project, maybe async_ssl?

**Comment by mseri** [comment]
Solved in conduit
