### ISSUE TITLE
lib/io.mli referenced in README does not exist

### ISSUE THREAD

**Issue by ciarand** [mirage/ocaml-cohttp#404]
[The README says](https://github.com/mirage/ocaml-cohttp/blob/748a5eb3b34c33475704c72475295e48a8d2adf4/README.md):

>You can implement other targets using the parser very easily. Look at the lib/IO.mli signature and implement that in the desired backend.

I don't see `lib/IO.mli`. Is this supposed to be `lib/s.mli` instead?

**Comment by avsm** [comment]
It is indeed, as it got renamed a few releases ago. Good catch!

**Comment by ciarand** [comment]
:+1:
