### ISSUE TITLE
Expose {Response,Request}.make_body_writer

### ISSUE THREAD

**Issue by samoht** [mirage/ocaml-cohttp#415]
Any reason why the `make_body_writer` have disappeared in 1.5.0? I use them in `ocaml-git` and the new interface doesn't seem to have a way to create `{Response,Request} .writer` anymore.

**Comment by rgrinberg** [comment]
I wanted to get in #410 for `0.19.0` which would bring back these functions. The reason for removing them in the first place was just to clean up in advance for this change. Didn't really expect it to impact anyone.

We can bring all this stuff back and make a point release. Or you can simply just use `Transfer_io.Make` yourself and import those functions (I believe Request/Response just re-exported them).

The ETA to get #410 into a mergeable state is by Monday. Although it will still need a little review.

**Comment by samoht** [comment]
ok, I was able to make some progress by using `Transfer_io`. But then I don't have a `write_footer` function anymore, so I had to copy/paste the function.

I'm fine to wait until monday to test the new IO layer.

**Comment by avsm** [comment]
sorry for jumping the gun on the release -- i wanted to get over the Lwt 2.5.0 hump as soon as possible. A point release off 0.18.3 probably would have been a better idea for that...

**Comment by samoht** [comment]
And then the `{Request,Response}.write_headers` are also missing and they are a bit more annoying to copy/paste. So no problem, I'll wait for the new IO :-)

**Comment by rgrinberg** [comment]
@samoht `{Request.Response}.write_headers` is equivalent to `IO.write (Header.to_string header)`

**Comment by samoht** [comment]
well not really, it doesn't take care of the response first line and adding the content-encoding headers.

**Comment by rgrinberg** [comment]
You're right. I confused what you mentioned with `Header_io.Make(IO).write`. Wtf is `write_headers` though, I can't find it anywhere in the history?

On August 5, 2015 at 8:04:10 PM, Thomas Gazagnaire (notifications@github.com) wrote:

well not really, it doesn't take care of the response first line and adding the content-encoding headers.

**Comment by rgrinberg** [comment]
@samoht Disregard my last post. Of course you meant `write_headers`. Yes these will be added in the new IO layer under `write_{req,rep}`. But all the HTTP related functionality has been moved outside the functors (e.g. messing around with headers).

**Comment by rgrinberg** [comment]
@samoht I'm reviewing git_http.ml to gain some understanding of how ocaml-git is using cohttp and I'm a bit puzzled by:

https://github.com/rgrinberg/ocaml-git/blob/master/lib/http/git_http.ml#L134-L135

What does "flushing" means here? `write_footer` only prints `0\r\n\r\n` on chunked requests/responses and it doesn't flush anything regardless. In any case, does ocaml-git really need control over printing this? That chunk should just ideally be part of the body rather than any footer.

**Comment by samoht** [comment]
This function just copies what `Request.write` [used to do](https://github.com/mirage/ocaml-cohttp/blob/master/lib/request.ml#L203). Seems that just the body were flushed (if `flush` is true), not sure why. And yes, the requests/responses are supposed to be chucked.

The smart HTTP protocols does some weird things for the server to not keep state. It simulates the following RPC:

- client sends A
- server replies with A'
- client sends B
- server replies with B'

By the following HTTP calls:

- client sends A
 - server replies with A'
- client sends AB
- server replies with A'B'

ocaml-git `Git_http`'s module makes that transformation transparent. Which means that it somehow needs low-level controls to start/stop request (I think).

**Comment by rgrinberg** [comment]
`Request.write` has been basically renamed to `Io.Make(IO).write_req`. Thanks for the explanation of how smart http works (there's very little information about it on the net). I'm still not sure why it's necessary to use `write_footer` manually and not just rely on `Request.write` to call it.

I'll play around with ocaml-git a little to see what can be done.

**Comment by yomimono** [comment]
@samoht can you either close this or comment (as briefly as you like) on what's still needed?  I suspect the issue is solved now.

**Comment by samoht** [comment]
Yes, I think this is not needed anymore now. /cc @dinosaure

**Comment by dinosaure** [comment]
The HTTP part of `ocaml-git` took a tuned abstraction of [webs](https://github.com/dbuenzli/webs) and an implementation of `cohttp >= 1.0.0`. So, this issue is done, I believe too.
