### ISSUE TITLE
Websocket broken with latest ocaml-cohttp

### ISSUE THREAD

**Issue by vbmithr** [mirage/ocaml-cohttp#423]
With no obvious fix.
I needed Cohttp_lwt_unix.{Request,Response}.write to boostrap with websocket protocol.
Those functions do not exist anymore.

**Comment by rgrinberg** [comment]
They still exist, they're just not exposed by default.

`Cohttp.{Request,Response}.Make(Cohttp_lwt_io).write`

**Comment by vbmithr** [comment]
Thanks!
