### ISSUE TITLE
Bottleneck performance on the size of POST data

### ISSUE THREAD

**Issue by herry13** [mirage/ocaml-cohttp#426]
Hi All, thank you for this great software. Currently, I'm investigating a performance bottleneck on processing the body of request to a Cohttp server. This is the codes which I used in my experiments:

```ocaml
open Lwt 
open Cohttp
open Cohttp_lwt_unix

let server () =
  let callback _ _ body =
    Cohttp_lwt_body.to_string body
    >|= (fun body -> Yojson.Basic.from_string body |> Yojson.Basic.to_string)
    >>= (fun body -> Server.respond_string ~status:`OK ~body ()) 
  in  
  Server.create ~mode:(`TCP (`Port 8010)) (Server.make ~callback ()) 

let () = ignore (Lwt_main.run (server ()))
```

The above "json echo" server is doing a simple job: it receives a request, reads and parses the body into JSON, and then generates and sends the JSON string back to the client as the response.

I have two JSON files (`file1.json`, `file2.json`) with different size, one is **1152** bytes, and another is **1153** bytes. I made two requests with curl using the above files:

```bash
curl -X POST -d @file1.json http://localhost:8010
curl -X POST -d @file2.json http://localhost:8010
```

Although the difference of the file sizes is very small (only 1 byte), but the response times that I got is quite significant:
- response time of `file1.json`: 0.018s
- response time of `file2.json`: 1.017s

Is there any explanation about this?

Please note that I have done experiments that directly parsed and generated the JSONs from a console application using Yojson. And the difference on the response times were insignificant. So I'm sure the bottleneck is not in Yojson.

Thank you.

**Comment by edwintorok** [comment]
The delay might be on curl's side waiting for a 100-continue that never arrives before sending the body. Try turning off the `Expect: 100-Continue`:
 `time curl -H "Expect:" -X POST -d @file2.json http://localhost:8010 -v`

**Comment by herry13** [comment]
@edwintorok Your suggestion is working. Thank you very much.
