### ISSUE TITLE
Add README usage examples

### ISSUE THREAD

**Issue by owainlewis** [mirage/ocaml-cohttp#43]
Hi. Thanks for your work : )

Would it be possible to add some simple documentation to the README? I.e very basic stuff like making basic requests. I've found it nearly impossible to find any easy to use libraries for OCaml that handle simple HTTP requests for newcomers like myself.

I'm thinking something along the lines of this which gives examples on how to do basic things:

https://github.com/dakrone/clj-http/blob/master/Readme.md

Thanks

**Comment by rgrinberg** [comment]
@owainlewis I've created a much more useful README. Don't hesitate to create more issues if you have any concrete suggestions for it.
