### ISSUE TITLE
Memory leak in cohttp.async

### ISSUE THREAD

**Issue by vbmithr** [mirage/ocaml-cohttp#433]
```ocaml
open Core.Std
open Async.Std
open Cohttp_async
let loop () =
  let uri = Uri.(of_string "https://www.okcoin.com/api/v1/trades.do?symbol=btc_usd") in
  let rec loop () =
    Client.get uri >>= fun (code, resp) ->
    Body.(to_string resp) >>= fun body ->
    ignore body;
    after @@ sec 2. >>= fun () ->
    loop ()
  in loop ()
let () =
  don't_wait_for @@ loop ();
  never_returns @@ Scheduler.go ()
```

When executing this program, the memory used is always growing.

**Comment by rgrinberg** [comment]
Is there a reason for the `eprintf` line?

I'd expect the leak to occur without it if it occurs.

**Comment by vbmithr** [comment]
No reason for the `eprintf` line. I'll try without it.

**Comment by vbmithr** [comment]
Tried to trace this but to no avail. I asked @OCamlPro-Bozman to have a look with ocp-memprof.

**Comment by rgrinberg** [comment]
@vbmithr 
* I was able to reproduce the exact leak you've shown here with cohttp master and the latest version of async_ssl
* I was unable to reproduce this leak with the lwt backend of cohttp and the openssl backend of conduit. And if there's a leak, it's far too slow for my patience to detect it

I've investigated a similar leak to this before and ended up determining  that the likely culprit is either async_ssl or conduit's bindings to it. I'm not quite sure which tools to use to get to the bottom of this however.

**Comment by vbmithr** [comment]
On 31/05/2016 07:36, Rudi Grinberg wrote:
> I'm not quite sure which tools to use to get to the bottom of this however.

spacetime, or the other memory profiler coded by @jhjourdan

Vincent

**Comment by vbmithr** [comment]
Cannot repro this bug anymore with latest janestreet dev packages and Cohttp (They claim they indeed fixed a memory leak issue in async-ssl).

I still have high memory consumption issues when using cohttp with the async backend but at least this trivial example does not produce a memory leak anymore. Closing.
