### ISSUE TITLE
compile (link) error "No implementations provided for the following modules"

### ISSUE THREAD

**Issue by domsj** [mirage/ocaml-cohttp#436]
I'm getting the following error
```
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Cohttp_lwt_body referenced from src/alba.cmx
         Cohttp_lwt_unix referenced from src/alba.cmx
Command exited with code 2.
Compilation unsuccessful after building 399 targets (0 cached) in 00:00:35.
make: *** [build-alba] Error 10
```
while trying to compile the (lwt http client) example from the README

https://github.com/openvstorage/alba/commit/d78586958a316a1176a2671837ea602a1505fb0d
https://api.travis-ci.org/jobs/87009551/log.txt?deansi=true

**Comment by rgrinberg** [comment]
You should use the lwt findlib subpackage `cohttp.lwt`

**Comment by domsj** [comment]
Thanks, also just found that out with the help of @toolslive.
Imo it makes sense to document that in the readme though, now it's not so user friendly.

**Comment by rgrinberg** [comment]
I'll close this once I updated the docs.
