### ISSUE TITLE
Cohttp async file descriptor leak

### ISSUE THREAD

**Issue by danielrichman** [mirage/ocaml-cohttp#444]
In Cohttp_async.Client.request,

``` ocaml
  let request ?interrupt ?(body=`Empty) req =
    (* Connect to the remote side *)
    Net.connect_uri ?interrupt req.Request.uri
    >>= fun (ic,oc) ->
    Request.write (fun writer -> Body.write Request.write_body body writer) req oc
    >>= fun () ->
    read_request ic >>| fun (resp, body) ->
    don't_wait_for (
      Pipe.closed body >>= fun () ->
      Deferred.all_ignore [Reader.close ic; Writer.close oc]);
    (resp, `Pipe body)
```

if `Request.write` or `read_request` raises (e.g., if the server drops the connection or sends you rubbish), then we'll never get to "Reader.close ic", and so we leak a file descriptor. 

I think there might be similar problems with other functions in that file.

**Comment by mseri** [comment]
This should have been fixed by https://github.com/mirage/ocaml-cohttp/pull/523
