### ISSUE TITLE
cohttp fail to compile on archlinux

### ISSUE THREAD

**Issue by c-cube** [mirage/ocaml-cohttp#462]
Cohttp, pulled as a dependency for the package `github` (itself used for opam-publish), fails to compile on arch with the following message:

> /home/simon/.opam/4.02.3/bin/ocamlfind ocamlopt -g -linkpkg -package base64 -package bytes -package cmdliner -package conduit.lwt-unix -package fieldslib -package fieldslib.syntax -package lwt -package lwt.unix -package magic-mime -package re.emacs -package sexplib -package sexplib.syntax -package stringext -package unix -package uri -package uri.services bin/cohttp_server.cmx lib/cohttp.cmxa lwt-core/cohttp_lwt.cmxa lwt/cohttp_lwt_unix.cmxa bin/cohttp_server_lwt.cmx -o bin/cohttp_server_lwt.native
/home/simon/.opam/4.02.3/lib/ssl/libssl_stubs.a(ssl_stubs.o): In function `get_method':
/home/simon/.opam/4.02.3/build/ssl.0.5.2/src/ssl_stubs.c:297: undefined reference to `SSLv3_client_method'
/home/simon/.opam/4.02.3/build/ssl.0.5.2/src/ssl_stubs.c:305: undefined reference to `SSLv3_method'
/home/simon/.opam/4.02.3/build/ssl.0.5.2/src/ssl_stubs.c:301: undefined reference to `SSLv3_server_method'
collect2: error: ld returned 1 exit status
File "caml_startup", line 1:
Error: Error during linking
Command exited with code 2.
Makefile:20: recipe for target 'build' failed

I also attach the [whole files]( resulting from the `opam install`.

[cohttp_files.zip](https://github.com/mirage/ocaml-cohttp/files/167350/cohttp_files.zip)

**Comment by edwintorok** [comment]
You need a newer `ocaml-ssl`: >= 0.5.2 https://github.com/savonet/ocaml-ssl/commit/8f698ba93028f0b399f75079d4369f44db82182c

**Comment by edwintorok** [comment]
This should've been fixed by https://github.com/savonet/ocaml-ssl/commit/8f698ba93028f0b399f75079d4369f44db82182c, but that is in `ocaml-ssl 0.5.2` already.
Either way this is an `ocaml-ssl` bug and not a cohttp bug.
How does your header look like on Arch Linux?
 `gcc -dD -E /usr/include/openssl/ssl.h`
 `gcc -dD -E /usr/include/openssl/ssl.h|grep OPENSSL_NO`

**Comment by c-cube** [comment]
Looks like this, there is indeed no SSLv3 support.
[openssl_state.txt](https://github.com/mirage/ocaml-cohttp/files/167403/openssl_state.txt)

**Comment by c-cube** [comment]
Note that I have `ssl 0.5.2`, which compiles perfectly well on my compute. The error occurs when compiling cohttp.

**Comment by c-cube** [comment]
Hmmm weird, reinstalling ssl (with the exact same version) seems to have fixed the issue.
