### ISSUE TITLE
Server example in readme does not typecheck

### ISSUE THREAD

**Issue by zenhack** [mirage/ocaml-cohttp#481]
When trying to compile the server example in the README, I get this error:

```
File "hello.ml", line 15, characters 22-41:
Error: This expression has type [> `TCP of [> `Port of int ] ]
       but an expression was expected of type Conduit_lwt_unix.server
```

Which does seem to be a genuine mistake in the program. Relevant type declaration:

https://github.com/mirage/ocaml-cohttp/blob/master/lwt/cohttp_lwt_unix.mli#L72

**Comment by zenhack** [comment]
Ack, so the problem seems to be linking against the wrong package. The above error is with:

```
ocamlbuild -pkg lwt -pkg cohttp hello.byte
```

However, running:

```
ocamlbuild -pkg cohttp.lwt hello.byte
```

succeeds. Sorry for the noise; still new to OCaml :\

Thoughts on including build instructions?

**Comment by rgrinberg** [comment]
Build instructions would be a nice addition. Mind making a PR?

Note that you can also use the `.native` extension to build a native code server. Which is probably the target most users expect.

**Comment by zenhack** [comment]
I opened pr #482. I'll go ahead and close this one.
