### ISSUE TITLE
ounit required by default due to Cohttp_test

### ISSUE THREAD

**Issue by avsm** [mirage/ocaml-cohttp#496]
E.g. see https://travis-ci.org/avsm/ocaml-cohttp/jobs/140757772

Tentative fix by moving the module out to lib_test is in avsm/ocaml-cohttp@5330792452dc3afdf0338d91f55fcbdb443dd74c

**Comment by rgrinberg** [comment]
This is not enough as you also need to move `cohttp_lwt_test` to its own directory (same for async).

This seems like an oasis bug though, so I just reverted back to the old generated code. It works fine now.

**Comment by avsm** [comment]
Ah yes, I see what you mean re: directory layout. Do you mean you regenerated the code with an old version of OASIS?

**Comment by rgrinberg** [comment]
This is no longer a problem since I've reverted the change which caused the generated code to change.
