### ISSUE TITLE
documentation of breaking changes?

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-cohttp#497]
do you keep track of changes?   I just stumbled upon `no such field uri` of `Request.t` (which was there in 0.20.x), and had to go through your commit logs to find out it was (first) renamed to `path`; then in another commit to `resource`.  it would be nice to keep track of such renames in your `CHANGES` file.

**Comment by avsm** [comment]
That should be clearly marked in the change log file, so this is a bug

**Comment by rgrinberg** [comment]
It's in the CHANGELOG but it's not marked as breaking. Should be a simple fix.

**Comment by hannesm** [comment]
which changelog are you talking about?  I found off the head this changes file https://github.com/mirage/ocaml-cohttp/blob/a1396d87c137e910f58ebfe4e040f54591235c78/CHANGES -- which does not contain any mention of `uri` now being different.

**Comment by rgrinberg** [comment]
This  is the relevant line:

https://github.com/mirage/ocaml-cohttp/blob/a1396d87c137e910f58ebfe4e040f54591235c78/CHANGES#L2

I agree that it's opaque and insufficient. Better would be to mark this as breaking and show users how to migrate (since it's trivial in this case)

**Comment by hannesm** [comment]
@rgrinberg oh, I didn't realise that it was talking about renames of uri in `Request.t`, sorry

**Comment by hannesm** [comment]
I'll close this issue, feel free to reopen if you're willing to improve the current state.  I discovered in the extensive CHANGES for 0.99 there were lots of deprecation warnings, but for 1.0 there was no clear "rewrite `Cohttp_lwt_body` to `Cohttp_lwt.Body`" -- which I had to do in various projects.  I like how OCaml does it with `*` and `-` for changes, would be great to adapt this.
