### ISSUE TITLE
Error: Unbound module Cohttp_lwt_unix

### ISSUE THREAD

**Issue by spencerwi** [mirage/ocaml-cohttp#502]
I've installed `cohttp` and `lwt` both via opam, and I have this in my `_tags` file:

```
true: package(cohttp), package(lwt), package(lwt.unix)
```

and in my `.merlin` file:

```
PKG cohttp lwt lwt.unix
```

At the top of `mycode.ml`, I have, exactly following the client sample from the README in this github repo:

```ocaml
open Lwt
open Cohttp
open Cohttp_lwt_unix

let download_templates =
    Client.get (Uri.of_string "https://www.gitignore.io/dropdown/templates.json") >>= fun (resp, body) ->
        body |> Cohttp_lwt_body.to_string >|= fun body -> body

let () =
    Lwt_main.run download_templates
    |> print_endline
```

When I try to run `ocamlbuild -use-ocamlfind mycode.native`, I get:

```
Error: Unbound module Cohttp_lwt_unix
```

I'm stumped. I've tried looking for a package by that name and various combinations of that name separated by dots and underscores and so on, but no luck. Am I doing something wrong, or has the codebase for cohttp changed in some subtle way?

**Comment by spencerwi** [comment]
Relevant after looking more myself: it works when I switch to 4.02.3, but not when I'm on `4.03.0+fp+flambda`

**Comment by hcarty** [comment]
Try using the `cohttp.lwt` package in your `.merlin` and `_tags` files. That should fix your issue.

**Comment by spencerwi** [comment]
Yeah, the combination of switching back to `4.02.3` and adding `cohttp.lwt` to my `.merlin` and `_tags` files fixes the issue. Not sure why `4.03.0` doesn't know about that module though.

**Comment by hcarty** [comment]
@spencerwi Maybe a library version conflict somewhere, leading opam to install of an older version of cohttp under 4.03.0?  That's just a guess but it's something I've seen before, particularly when camlp4 or ppx dependencies are involved.

**Comment by spencerwi** [comment]
Thanks for the suggestion! I'll take a closer look at my installed libs to see if something's up. At least the opam switch to 4.02.3 works, so I'm able to keep on moving.
