### ISSUE TITLE
newline at the end of strings in Header.to_lines 

### ISSUE THREAD

**Issue by zoggy** [mirage/ocaml-cohttp#519]
Hello,

I used `Cohttp.Header.to_lines` to retrieve the list of header fields as a list of strings. I passed this list of strings to `Curl.set_httpheader`. It tooks me some time to find out why my queries were failing strangely. The strings returned by `Cohttp.Header.to_lines` end with `\r\n`. Since the fields are in the form of a list, I did not expect this behaviour. 

Is there any hope to change that behaviour ? (it may be too late) If not, I think a note in the documentation should be added about this (I can make a PR, just tell me).

**Comment by rgrinberg** [comment]
The other alternative here is to add a new function to Header. Something like `to_frames` for example. I can see how a name like `to_lines` might make this point about newlines ambiguous.

**Comment by rgrinberg** [comment]
Actually, this function is part of the private api and you're free to change it as you wish - just make sure the rest of cohttp doesn't break. PR's are welcome.
