### ISSUE TITLE
Lwt streaming responses and flush exceptions

### ISSUE THREAD

**Issue by mattjbray** [mirage/ocaml-cohttp#529]
Continued from #528, responding to @rgrinberg.

> But I'm wondering, why do we need to make the connection closing event part of the api at all?

This is the use-case:

When the client connects, I want to start some concurrent worker threads. As each thread completes, I want to stream its result to the client. The order in which the client receives the results does not matter. If the client disconnects, I want to cancel the remaining threads.

```ocaml
open Lwt.Infix
open Cohttp
open Cohttp_lwt_unix

let server =
  let callback _conn req body =
    (* Create a stream for the response and a push function. *)
    let result_stream, push_result = Lwt_stream.create () in

    (* A worker thread. Perform some work and then push the result onto the
       stream.
    *)
    let do_work i seconds =
      Lwt_unix.sleep seconds >>= fun () ->
      Lwt_log.notice_f "Pushing %i" i >>= fun () ->
      push_result (Some (string_of_int i ^ "\n")) |> Lwt.return
    in

    (* Create a thread that starts some workers, then waits for them to
       complete.
    *)
    let workers =
      [2.0; 1.0; 3.0]
      |> List.mapi do_work
      |> Lwt.join
    in

    (* When all the workers are done, end the stream by pushing None. *)
    let () =
      Lwt.async
        (fun () ->
           Lwt.finalize
             (fun () -> workers)
             (fun () ->
                Lwt_log.notice "Closing stream" >>= fun () ->
                push_result None |> Lwt.return)
        )
    in

    (* Respond with the stream. *)
    let body = Cohttp_lwt_body.of_stream result_stream in

    Server.respond ~status:`OK ~body ()
  in

  (* Catch exceptions while flushing results to the client.

     Without this, the server will crash if the client disconnects before the
     stream has finished.
  *)
  let on_exn exn = Lwt_log.ign_error ~exn "Unhandled exception" in

  Server.create ~mode:(`TCP (`Port 8000)) ~on_exn (Server.make ~callback ())

let () = ignore (Lwt_main.run server)
```

We can tell that the client has disconnected when Cohttp tries to flush the next result an encounters an exception.

So, the missing piece is to call `Lwt.cancel worker` if there is an exception while flushing a result to the client.

It is now possible to implement this using the process described in #528 - maintain a map of connections to `worker` threads, and cancel them in `conn_closed`. But this doesn't feel very nice, or safe.

What might be nicer is a `this_conn_closed` hook, which the user returns from `callback`.

> After looking at WAI in Haskell, I don't see a way to intercept a connection being closed either but that doesn't seem to cause any issues.

Great suggestion to look at WAI. WAI solves this problem by giving the user access to `write` and `flush` functions directly: see [`StreamingBody`][1] and [`responseStream`][2]. So the user is able to catch exceptions arising from a `flush` directly in the callback. In Cohttp the flush is outside of the user's control, which is why we have these indirect, global `on_exn` and `conn_closed` hooks.

What an API like this might look like for Cohttp:

```ocaml
(* Cohttp_lwt_body.mli *)
type t = [
  | Body.t
  | `Stream of ((string -> unit) -> (unit -> unit) -> unit Lwt.t)
] [@@deriving sexp]
```

```ocaml
(* Respond with the stream *)
let body =
  `Stream (fun write flush ->
      (* Note that an Lwt_stream is not really necessary; this just fits in with
         my example above.
      *)
      result_stream
      |> Lwt_stream.iter (fun result ->
          write result;
          try flush () with
          | exn -> (Lwt.cancel worker; raise exn)
        )
    )
in
```

[1]: https://hackage.haskell.org/package/wai-3.2.1.1/docs/Network-Wai.html#t:StreamingBody
[2]: https://hackage.haskell.org/package/wai-3.2.1.1/docs/Network-Wai.html#v:responseStream

**Comment by andreas** [comment]
I think this PR can be closed (according to this [comment](https://github.com/mirage/ocaml-cohttp/pull/647#issuecomment-436979312) with #647 merged).
