### ISSUE TITLE
Cannot install cohttp 0.22.0 with OCaml 4.02.3

### ISSUE THREAD

**Issue by zepalmer** [mirage/ocaml-cohttp#541]
cohttp 0.22.0 will not install on my system using OCaml 4.02.3.  I am using Debian Jessie with OPAM v1.2.2.  It seems that this has to do with the `Uchar` compatibility module, though I'm not clear on what that module is doing or how it could be causing a problem.  Fortunately, the steps to reproduce are pretty simple:

```
$ export OPAMROOT=$HOME/temp-opam-root
$ mkdir -p "$OPAMROOT"
$ opam init --comp=4.02.3
$ opam install cohttp
```

The above will fail with a message similar to the following:

```
# File "_none_", line 1:
# Error: No implementations provided for the following modules:
#          Uchar referenced from /home/zpalmer/.opam/4.02.3/lib/fmt/fmt.cmxa(Fmt)
# Command exited with code 2.
```

This is a problem for any OCaml compiler with version <4.03.0.  Using 4.04.0+flambda, for instance, it is possible to install cohttp.

Thank you!

**Comment by dbuenzli** [comment]
This is due to a missing dependency in `Fmt`'s `META` file. This should be fixed once https://github.com/ocaml/opam-repository/pull/8761 is merged. Meanwhile if you can live with a pin just do 

```
opam pin add --dev-repo fmt
```

it should solve the problem.

**Comment by zepalmer** [comment]
Excellent; thank you for the info!  I'll close the issue, but hopefully your response will save someone else the time that I spent on this today.  :)

**Comment by dbuenzli** [comment]
> the time that I spent on this today. :)

Sorry about that.

**Comment by zepalmer** [comment]
Not your fault!  And thank you so much for the response; I'm genuinely hoping it helps someone else out and I think it's a contribution.  I spend a while on Google and got nowhere with this.  Perhaps now your answer will be available to others (including me in a month when I invariably forget what happened).  :+1:  :-D

**Comment by dbuenzli** [comment]
> Not your fault!

Well in this case, it is...

**Comment by zepalmer** [comment]
Ah!  I hadn't realized you're maintaining `fmt` as well.  :)  Nonetheless, I appreciate the help (and the nifty libraries)!
