### ISSUE TITLE
Does `Deferred.any` is the best practice for timeout request?

### ISSUE THREAD

**Issue by liweijian** [mirage/ocaml-cohttp#569]
I just did [some search](https://github.com/mirage/ocaml-cohttp/search?utf8=%E2%9C%93&q=timeout&type=) and found no answer.

I was wondering if maybe the method mentioned by [RWO](https://realworldocaml.org/v1/en/html/concurrent-programming-with-async.html) which uses `Deferred.any` is the best practice?

```ocaml
let get_definition_with_timeout ~server ~timeout word =
  Deferred.any
    [ (after timeout >>| fun () -> (word,Error "Timed out"))
    ; (get_definition ~server word
       >>| fun (word,result) ->
       let result' = match result with
         | Ok _ as x -> x
         | Error _ -> Error "Unexpected failure"
       in
       (word,result')
      )
    ]
```

**Comment by rgrinberg** [comment]
Probably not. Because this doesn't guarantee that resources will be cleaned up. The cohttp API currently has some flaws around this. But the best way to do this will be to provide a deferred to `?interrupt` that you will fill after your timeout.

**Comment by liweijian** [comment]
@rgrinberg Thanks:)

I just did some search on [interrupt](https://github.com/mirage/ocaml-cohttp/search?utf8=%E2%9C%93&q=interrupt&type=), but I couldn't find any comments or example of using it.

Would you mind to give me some advise?

**Comment by liweijian** [comment]
@rgrinberg Great thanks for your reply, I just read some code of [async_unix](https://github.com/janestreet/async_unix), and the following comment gave me light

> when [interrupt] becomes determined

Here is what I learned 

```ocaml
  let%bind _, body = Cohttp_async.Client.get 
    ~interrupt:(after (sec 2.0) >>| fun ()->Log.debug logger "Timeout with url:%s" url) uri
```
