### ISSUE TITLE
Location of 'cohttp-lwt-js'

### ISSUE THREAD

**Issue by floydianslips** [mirage/ocaml-cohttp#599]
I have hit a roadblock while trying to muddle through compiling. The code I am trying to use calls 'cohttp.js' and ocamlfind cannot locate 'cohttp-lwt-js'. I notice in your META.cohttp.template
 file it mentions 'cohttp.js' as being deprecated and to use 'cohttp-lwt-js'. I cannot find this anywhere. the only mention of it I can find is in that file. It is not a package associated with cohttp as far as I can tell. Although I am clueless I am desperately trying to get this application up and running. Thanks for any help.

_ocamlfind ocamlc -thread -package js_of_ocaml,js_of_ocaml.syntax,cohttp.lwt,cohttp.async,lwt.ppx,cohttp.js,yojson -syntax camlp4o -c grid.mli
ocamlfind: Package `cohttp-lwt-js' not found - required by `cohttp.js'
Makefile:14: recipe for target 'grid.cmo' failed
make: *** [grid.cmo] Error 2_

**Comment by rgrinberg** [comment]
You should use the `cohttp-lwt-jsoo` rather than `cohttp.js`. But this is indeed a bug in our META. I'll push a fix to master.

**Comment by rgrinberg** [comment]
950f58d04fc3052086a98506d40d025b75a2f892 fixes this.
