### ISSUE TITLE
regress test for chunked-encoding off-by-one

### ISSUE THREAD

**Issue by avsm** [mirage/ocaml-cohttp#60]
This is almost certainly using a very old version of Cohttp, but we should add a regression test to verify that this doesn't affect current Cohttp servers.

See lavv17/lftp#51 for the details of the bug.

In a nutshell

```
get http://mjambon.com/releases/cppo/cppo-0.9.3.tar.gz
```

a content-length calculation with a HEAD request is different from a chunked-encoding transfer.

**Comment by rgrinberg** [comment]
In the linked ticket, I assume the server in question is written in cohttp. Right?

**Comment by rgrinberg** [comment]
Closing until there's more information.
