### ISSUE TITLE
Error: Required module `Cohttp__' is unavailable

### ISSUE THREAD

**Issue by tempodox** [mirage/ocaml-cohttp#600]
I'm getting “Error: Required module `Cohttp__' is unavailable” after upgrading to 1.0.2 on macOS.

And also,

No implementations provided for the following modules:
         Cohttp_lwt_unix__ referenced from mysource.cmx
         Cohttp__ referenced from mysource.cmx

**Comment by rgrinberg** [comment]
You need to pin jbuilder beta17 and reinstall cohttp. Sorry about that. We will have a jbuilder fix out for this very soon.

**Comment by tempodox** [comment]
Yep, that works. Thanks!
