### ISSUE TITLE
Compilation Fails with cohttp-lwt-unix=1.0.2, But Succeeds When Using 1.0.0

### ISSUE THREAD

**Issue by ode79** [mirage/ocaml-cohttp#601]
I get the below errors when using cohttp-lwt-unix=1.0.2 as a dependency of my project, but downgrading to 1.0.0 and the compilation succeeds.

$ ocamlbuild -use-ocamlfind themoviedb.native
+ ocamlfind ocamlopt -linkpkg -package cohttp-lwt-unix -package yojson -package ppx_deriving_yojson themoviedb.cmx -o themoviedb.native
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Cohttp_lwt_unix__ referenced from themoviedb.cmx
         Cohttp__ referenced from themoviedb.cmx
Command exited with code 2.
Compilation unsuccessful after building 4 targets (0 cached) in 00:00:01.

**Comment by waclena** [comment]
Same problem here, on two Arch Linux boxes, in both a 4.04.2 and
4.05.0 switch, with all of my cohttp apps (which all compiled just
fine before the upgrade).  Except for me, downgrading to 1.0.0 doesn't
help.  I still get:

```
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Cohttp_lwt_unix__ referenced from client_example.cmx
         Cohttp_lwt__ referenced from client_example.cmx
         Cohttp__ referenced from client_example.cmx
Command exited with code 2.
```

This is from the client_example.ml code from the README.md, compiled
with the suggested ocamlbuild command, but I get the same or similar
errors with all my projects.

On a FreeBSD box with cohttp.1.0.2, I can still compile my
applications.

**Comment by avsm** [comment]
This is a bug with jbuilder beta18. If you `opam install jbuilder.1.0+beta17` it should work fine.  A fixed beta19 of jbuilder will be out very soon we hope.

**Comment by waclena** [comment]
Thanks Anil!  This worked for me:

```
opam install jbuilder.1.0+beta17
opam install cohttp-lwt-unix.1.0.2 cohttp.1.0.2 cohttp-lwt.1.0.2
```

**Comment by ode79** [comment]
Installing jbuilder.1.0+beta17 works for making my library compile (this downgrades cohttp-lwt-unix). But then I am getting another problem when using another project that uses the library I have just compiled. Now I am getting the error "Fatal error: exception (Failure "No SSL or TLS support compiled into Conduit").

**Comment by hcarty** [comment]
@ode79 You'll need to install the `tls` or `ssl` opam package to get HTTPS server or client support from cohttp.

**Comment by ode79** [comment]
@hcarty Thanks, this works.
I didn't have to manually install tls before when I originally developed my library with cohttp 0.22.0 and conduit 0.15.0.

**Comment by hcarty** [comment]
There were pre-1.x changes in how ssl/tls were handled.  I don't remember the specifics though.  Glad it's working for you now!
