### ISSUE TITLE
Cohttp.Request.t does not keep scheme from given uri

### ISSUE THREAD

**Issue by andersfugmann** [mirage/ocaml-cohttp#615]
Cohttp.Request.make takes an uri, but strips the scheme, so its e.g. not possible to know if the request is http or https. For my use case, it limits the usefulness of  Cohttp.Request.t structure, as I need to pass an uri around along with it (or at least the scheme). 

If the datastructure is extended to hold the scema, it should of course also be used used by e.g. ` Cohttp_async.Client.request

**Comment by mseri** [comment]
This is fixed in the upcoming release
