### ISSUE TITLE
Problem making a request to Zendesk that doesn't happen with curl

### ISSUE THREAD

**Issue by dwwoelfel** [mirage/ocaml-cohttp#624]
I'm having a problem making a POST request to Zendesk.

If I use curl, everything works fine:

```
~ $ curl -X POST "https://dww-test.zendesk.com/oauth/tokens"
{"error":"invalid_request","error_description":"'client_id', 'grant_type' required."}
```

If I use cohttp, I get a 403 forbidden response from Zendesk:

```
~ $ CONDUIT_DEBUG=true COHTTP_DEBUG=true cohttp-curl-async -X POST "https://dww-test.zendesk.com/oauth/token
s"                                                                                                          
cohttp-curl-async: [DEBUG] 17946 >>> POST /oauth/tokens HTTP/1.1

cohttp-curl-async: [DEBUG] 17946 >>> connection: close
host: dww-test.zendesk.com
user-agent: ocaml-cohttp/1.1.0


cohttp-curl-async: [DEBUG] 17946 >>> 
cohttp-curl-async: [DEBUG] <<< HTTP/1.1 403 Forbidden
cohttp-curl-async: [DEBUG] <<< Server: cloudflare
cohttp-curl-async: [DEBUG] <<< Date: Wed, 27 Jun 2018 19:57:07 GMT
cohttp-curl-async: [DEBUG] <<< Content-Type: text/html
cohttp-curl-async: [DEBUG] <<< Content-Length: 167
cohttp-curl-async: [DEBUG] <<< Connection: close
cohttp-curl-async: [DEBUG] <<< CF-RAY: 431a7b1aae3a288e-SJC
cohttp-curl-async: [DEBUG] <<< 
cohttp-curl-async: [INFO] cf-ray: 431a7b1aae3a288e-SJC
cohttp-curl-async: [INFO] connection: close
cohttp-curl-async: [INFO] content-length: 167
cohttp-curl-async: [INFO] content-type: text/html
cohttp-curl-async: [INFO] date: Wed, 27 Jun 2018 19:57:07 GMT
cohttp-curl-async: [INFO] server: cloudflare
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

There are a couple of headers that are slightly different, like the user-agent. I've tried setting all of the headers exactly the same as curl sets, but it doesn't help. I don't get a 403 with curl when I make the curl headers match the cohttp headers. 

Any ideas how I can debug this?

**Comment by avsm** [comment]
Could you also post the output of the `curl` request with `-vv` so we can see those request/response headers as well?

**Comment by avsm** [comment]
This looks to be due to some difference at the TLS negotiation level triggering the Cloudflare protection. It gets further when using the lwt version with openssl

```
env CONDUIT_DEBUG=true COHTTP_DEBUG=true cohttp-curl-lwt -X POST "https://dww-test.zendesk.com/oauth/tokens"
...
Client POST returned: 400 Bad Request
```

**Comment by jdpopkin** [comment]
For anyone running into issues like this on a ZenDesk integration that worked fine before, it might be helpful to know that [ZenDesk has been rolling out changes to their DDoS and abuse protection system since March of this year](https://support.zendesk.com/hc/en-us/articles/360001781967-Zendesk-rolls-out-new-DDoS-protection-and-abuse-prevention-system). That article's vague, but it implies that you may need to make configuration changes or client upgrades to keep SSL negotiation from breaking.

**Comment by emillon** [comment]
That seems to be the same issue as https://discuss.ocaml.org/t/ssl-error-using-cohttp-async/2433/3. I debugged that a bit and indeed, the SNI extension is not sent by the async backend. I have a working patch, I'll open a PR ASAP!
