### ISSUE TITLE
Odd ppx_type_conv dependency

### ISSUE THREAD

**Issue by copy** [mirage/ocaml-cohttp#626]
In opam-repository, cohttp depends on ppx_type_conv: https://github.com/ocaml/opam-repository/blob/master/packages/cohttp/cohttp.1.1.0/opam#L28

I believe this dependency is incorrect, as cohttp doesn't provide any ppxs. But even if it is correct, it should be changed as to ppxlib, as ppx_type_conv is deprecated.

**Comment by rgrinberg** [comment]
This was recently fixed in master actually.

**Comment by yminsky** [comment]
Can someone cut a release? This is still a problem in opam.
