### ISSUE TITLE
Installation fails with opam on OS X  

### ISSUE THREAD

**Issue by DavideDelVecchio** [mirage/ocaml-cohttp#638]
Hi ,
The installation of cohttp fails on OS X with the following characteristics 
Mac OS X 10.11.6
ocaml --version 4.07.0
opam --version 2.0.0
running 
opam install cohttp 
results in

[ERROR] The sources of the following couldn't be obtained, aborting:
          - cohttp.1.1.1: Download command failed
Any help appreciated 
Thanks

**Comment by mseri** [comment]
Thanks for the report. The bug is known and related to supported hashes in the `openssl` version shipped with OS X. It should be fixed in opam 2.0.1 (https://github.com/ocaml/opam/pull/3543) that should be released by the end of next week

**Comment by mseri** [comment]
A possible workaround could be to use the dev version of opam2, or to modify `~/.opam/repo/default/packages/cohttp/cohttp.1.1.1/opam` and remove the `sha512` hash line (you will likely need to modify other opam files containing sha512 or sha256 lines though)

**Comment by mseri** [comment]
Should be fixed once https://github.com/ocaml/opam-repository/pull/12826 is merged

**Comment by mseri** [comment]
@DavideDelVecchio can you try to run `opam update` and then `opam install cohttp`? We just released a new version of cohttp providing only the md5 hash, this should be available on all versions of osx.

**Comment by danielepiccone** [comment]
Came here because I had the same issue, I just managed to install the library following the steps @mseri suggested.  

Mac OSX 10.10.5
opam --version 2.0.0
The OCaml toplevel, version 4.07.0

**Comment by mseri** [comment]
Thanks!

**Comment by DavideDelVecchio** [comment]
I had it working now as per your previous message ,  thanks for your help
