### ISSUE TITLE
Inconsistency in dune-release tarballs

### ISSUE THREAD

**Issue by Zimmi48** [mirage/ocaml-cohttp#646]
Hi,

Most released versions have a dune-release tarball named `cohttp-1.x.x.tbz` but version 1.1.1 has none and version 1.2.0 has a tarball named `cohttp-v1.2.0.tbz`. This inconsistency is quite annoying for package managers. Could you fix it by:

- uploading a release tarball `cohttp-1.1.1.tbz` for version 1.1.1;
- uploading a release tarball `cohttp-1.2.0.tbz` for version 1.2.0 (probably not a good idea to remove the existing one if people are already relying on it)?

Thanks!

**Comment by Zimmi48** [comment]
The same problem also appears with the latest release of conduit.

**Comment by mseri** [comment]
Thanks for the report. I have added the tarballs and will see what we can do to avoid further issues, all the new releases are likely to be done with `dune-release`. Please open an issue on the `conduit` repository, I don't have access to that repository

**Comment by Zimmi48** [comment]
Thanks!

**Comment by djs55** [comment]
@Zimmi48 I've uploaded `conduit-1.3.0.tbz` -- let me know if you have any other issues with that repository.
