### ISSUE TITLE
Fatal error: exception SSL: Method error

### ISSUE THREAD

**Issue by VShingala** [mirage/ocaml-cohttp#653]
I am trying to build and run code suggested on GitHub page of ocaml-cohttp for downloading the reddit frontpage. I am able to build it but on running  I get this error "Fatal error: exception SSL: Method error". I tried installing tls using "opam install tls" also I have ssl and lwt_ssl installed. But it is giving same error. I am using ubuntu 18.04. 

Although I am able to get response from http webpages.

**Comment by talex5** [comment]
I got this too. The error is coming from the `ssl` library, so I guess your system isn't using `tls` (installing that fixed it for me).

**Comment by mseri** [comment]
This should be fixed in recent releases
