### ISSUE TITLE
Installation process not updated in README

### ISSUE THREAD

**Issue by ulugbekna** [mirage/ocaml-cohttp#657]
I followed the installation process in the readme file in project's root and opam installed cohttp. However, when I tried to run the `server_example.ml` snippet from the same readme, I ran into a problem that Cohttp_lwt_unix could not be found by Dune. Turned out that `cohttp` and `cohttp_lwt_unix` are separate libraries in opam and need to be installed separately. I think indicating this fact in the readme could be of great help for newcomers such as me. 

It could also help to explain the interplay between parts of cohttp, e.g. cohttp, cohttp_lwt, cohttp_lwt_unix. Such explanation is available in Opam package pages, but they are not where a newcomer looks first.

**Comment by mseri** [comment]
Fixed in upcoming release
