### ISSUE TITLE
Cohttp_async_lib.Body.is_empty wrong result

### ISSUE THREAD

**Issue by thedufer** [mirage/ocaml-cohttp#660]
I noticed some unexpected results from the async version of `Body.is_empty` (I have not looked at the corresponding lwt function).  In particular, the following bodies return the opposite of what I'd expect:

```
`Strings [ "" ] -> false
`Pipe (Pipe.of_list []) -> false
`Pipe (Pipe.of_list [ ""; "hi" ]) -> true
```

I assume the first one comes from the generic `Body` implementation, while the latter two are presumably async-specific.

**Comment by anuragsoni** [comment]
I think #712 resolves this problem. I'll make a follow up PR to discuss whether to consider `Strings [""]` and the corresponding async/lwt options as empty.

**Comment by thedufer** [comment]
@anuragsoni I haven't run a test, but based on the diff in that PR it looks like

```
`Pipe (Pipe.of_list [ "" ])`
```

will appear as non-empty, which doesn't seem correct to me.  I would expect `Body.is_empty x` to match `Body.to_string x |> String.is_empty`.

**Comment by anuragsoni** [comment]
@thedufer I kept that change as a separate PR at https://github.com/mirage/ocaml-cohttp/pull/713 Since that involves changes async, Lwt and the core Cohttp body.

**Comment by anuragsoni** [comment]
That still doesn’t cover the case where like you showed once created a body directly with the poly variant. Not sure that can be prevented without making the body type private.

**Comment by thedufer** [comment]
I don't understand why `Body.is_empty` doesn't just continue consuming from the pipe until it either finds a non-empty string or EOF.  That would get the correct behavior in all cases.  Only guarding `of_pipe` has the issue you note around directly creating the poly variant, but it also has issues if the data on the wire deserializes into the same thing, which seems like a real concern.  There's also non-zero overhead to doing the filtering.

**Comment by anuragsoni** [comment]
> I don't understand why `Body.is_empty` doesn't just continue consuming from the pipe until it either finds a non-empty string or EOF.

Agreed. Consuming empty strings here should be fine i believe. That will indeed cover the scenario you mentioned. I don't see other places in the current implementation of bodies where leaving `""` in the pipe/stream will cause issues, but i can double check. Thanks for the feedback, i'll update the PR to consume empty strings inside `is_empty`

**Comment by mseri** [comment]
This should be fixed in the next release
