### ISSUE TITLE
Unexpected channel closing error when using `write_body`

### ISSUE THREAD

**Issue by leamingrad** [mirage/ocaml-cohttp#665]
# Summary

When using `Cohttp_lwt.Body.write_body` to stream a response into an `Lwt.io` stream, the following error is seen:

```
[WARNING] Closing channel failed: Unix.Unix_error(Unix.EBADF, "check_descriptor", "")
```

# More Details

The error can be hit using the following minimum working example script:

```ocaml
(* client_example.ml *)
open Lwt
open Cohttp
open Cohttp_lwt_unix

let setup_logging () =
  Logs.set_level (Some Logs.Debug);
  Logs.set_reporter (Logs.format_reporter ())

let write_body_data data =
  Lwt_io.print data
  (* Uncomment the below to fix the issue *)
  (* >>= fun _ ->
  Lwt_io.(flush stdout)*)

let main =
  let url = Uri.of_string "http://localhost/ip" in
  Client.get url >>= fun (resp, body) ->
  Cohttp_lwt.Body.write_body write_body_data body

let () =
  let _ = setup_logging () in
  Lwt_main.run main
```

This can be compiled with `ocamlbuild -pkgs "cohttp-lwt-unix,logs" client_example.native`. I use a local [`httpbin`](https://httpbin.org/) instance (`docker run -p 80:80 kennethreitz/httpbin`) to provide the `/ip` endpoint, but this seems to happen against any server

# Debugging Attempts

I have looked into this issue a bit, and come up with the following:
* The logging statement that is producing the warning is the one in [`net.ml`](https://github.com/mirage/ocaml-cohttp/blob/master/cohttp-lwt-unix/src/net.ml)
* This seems to be something to do with conflicting `Lwt.io` streams - if `Lwt.(flush stdout)` is called in the `write_body_data` function then the problem disappears. Ditto if `Printf.printf` is used rather than `Lwt_io.print`
* I don't think that this is a regression - my guess is that this has always been an issue but the new warnings in #592 have made it more visible

Any help with this issue is appreciated. In particular, if it is not possible to fix, what would a good workaround be? I would like to keep using `write_body` if possible, but am worried that just adding `Lwt_io.flush` to the my function would cause problems.

**Comment by avsm** [comment]
I see this too, in the opam-ci that I just rebuilt. Bisecting cohttp versions now to see when it appeared...

**Comment by talex5** [comment]
You can reproduce this just using the client example in the README, if you:

1. Enable logging at the start.
2. Call `Gc.full_major ()` at the end.

```ocaml
let () =
  Fmt_tty.setup_std_outputs ();
  Logs.(set_level (Some Info));
  Logs.set_reporter (Logs_fmt.reporter ())

open Lwt
open Cohttp
open Cohttp_lwt_unix

let body =
  Client.get (Uri.of_string "https://www.reddit.com/") >>= fun (resp, body) ->
  let code = resp |> Response.status |> Code.code_of_status in
  Printf.printf "Response code: %d\n" code;
  Printf.printf "Headers: %s\n" (resp |> Response.headers |> Header.to_string);
  body |> Cohttp_lwt.Body.to_string >|= fun body ->
  Printf.printf "Body of length: %d\n" (String.length body);
  body

let () =
  let body = Lwt_main.run body in
  print_endline ("Received body\n" ^ body);
  Gc.full_major ()
```

Result:

```
...
script></body></html>
main.exe: [WARNING] Closing channel failed: Unix.Unix_error(Unix.EBADF, "check_descriptor", "")
```

`read_response` calls `closefn` in many places and doesn't seem to care whether it calls it twice.

https://github.com/mirage/ocaml-cohttp/blob/81bc7751278b01af78ddcb8d7abdac19f1bbdb05/cohttp-lwt/src/client.ml#L16-L42

**Comment by hcarty** [comment]
@talex5 I'm not able to reproduce this locally using the most recent releases of ocaml-tls 0.10.4 + conduit-lwt-unix 2.0.1 + cohttp-lwt-unix 2.3.0.  Is it possible you're using an older release of one or more of those?  conduit and tls have both had recent updates to fix issues with double-closing file descriptors.

**Comment by talex5** [comment]
I was testing with:

```
cohttp                  2.2.0       An OCaml library for HTTP clients and servers
cohttp-lwt              2.2.0       CoHTTP implementation using the Lwt concurrency library
cohttp-lwt-unix         2.2.0       CoHTTP implementation for Unix and Windows using Lwt
conduit                 1.5.0       A network connection establishment library
conduit-lwt             1.5.0       A portable network connection establishment library using Lwt
conduit-lwt-unix        1.5.0       A network connection establishment library for Lwt_unix
```

Upgrading cohttp didn't make a difference, but upgrading tls from 0.10.3 to 0.10.4 (and keeping everything else the same) seems to make the warning go away:

```
$ opam list|egrep '(cohttp|conduit|tls)'
cohttp                  2.3.0       An OCaml library for HTTP clients and servers
cohttp-lwt              2.3.0       CoHTTP implementation using the Lwt concurrency library
cohttp-lwt-unix         2.3.0       CoHTTP implementation for Unix and Windows using Lwt
conduit                 1.5.0       A network connection establishment library
conduit-lwt             1.5.0       A portable network connection establishment library using Lwt
conduit-lwt-unix        1.5.0       A network connection establishment library for Lwt_unix
tls                     0.10.3      Transport Layer Security purely in OCaml

$ dune exec ./main.exe
main.exe: [WARNING] Closing channel failed: Unix.Unix_error(Unix.EBADF, "check_descriptor", "")
Response code: 200
Headers: ...
Body of length: 526845
Received body
...
main.exe: [WARNING] Closing channel failed: Unix.Unix_error(Unix.EBADF, "check_descriptor", "")

$ opam upgrade tls
The following actions will be performed:
  ↗ upgrade   tls              0.10.3 to 0.10.4
  ↻ recompile conduit-lwt-unix 1.5.0            [uses tls]
  ↻ recompile cohttp-lwt-unix  2.3.0            [uses conduit-lwt-unix]
===== ↻ 2   ↗ 1 =====
Do you want to continue? [Y/n] y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[cohttp-lwt-unix.2.3.0] found in cache
[conduit-lwt-unix.1.5.0] found in cache
[tls.0.10.4] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
⊘ removed   cohttp-lwt-unix.2.3.0
⊘ removed   conduit-lwt-unix.1.5.0
⊘ removed   tls.0.10.3
∗ installed tls.0.10.4
∗ installed conduit-lwt-unix.1.5.0
∗ installed cohttp-lwt-unix.2.3.0
Done.
# Run eval (opam env) to update the current shell environment

$ dune exec ./main.exe
Response code: 200 
Headers: ...
Body of length: 527314
Received body
...
```

**Comment by hcarty** [comment]
https://github.com/mirleft/ocaml-tls/pull/397 is probably what fixed the issue in that case.

**Comment by leamingrad** [comment]
I can confirm that both my MWE above and the errors we were seeing in production are fixed after upgrading `tls` to the latest version (in fact the MWE is fixed without that upgrade), so I am closing the issue.
