### ISSUE TITLE
Cohttp.Request.make discards protocol, downgrading to http

### ISSUE THREAD

**Issue by emillon** [mirage/ocaml-cohttp#670]
Hi,

I'm using `Cohttp.Request.make` to build a request and run it later with `Cohttp_async.Client.request`. However, it seems that the protocol part of the uri is not kept, which causes a downgrade to plain HTTP.

See for example this program:

```ocaml
let () =
  let open Async.Deferred in
  let request = Cohttp.Request.make (Uri.of_string "https://github.com") in
  Format.printf "%a\n" Uri.pp_hum (Cohttp.Request.uri request);
  Async.Thread_safe.block_on_async_exn (fun () ->
      Cohttp_async.Client.request request >>| fun (resp, _) ->
      Cohttp.Response.status resp
      |> Cohttp.Code.code_of_status |> Format.printf "%d\n")
```

It displays:

```
//github.com/      
301
```

(and `tcpdump` confirms that http://github.com was hit, which replies with a redirect to https)

Thanks!

**Comment by dinosaure** [comment]
You can enforce `https` with the `?uri` argument:

```ocaml
let () =
  let open Async.Deferred in
  let uri = Uri.of_string "https://github.com" in
  let request = Cohttp.Request.make uri in
  Format.printf "%a\n" Uri.pp_hum (Cohttp.Request.uri request);
  Async.Thread_safe.block_on_async_exn (fun () ->
      Cohttp_async.Client.request ~uri request >>| fun (resp, _) ->
      Cohttp.Response.status resp
      |> Cohttp.Code.code_of_status |> Format.printf "%d\n")
```

But of course, it's not a proper solution and we should upgrade API (and keep `uri` inside the `Request.t`).

**Comment by emillon** [comment]
Yep I'll store `(request, url)` in the meantime.

**Comment by avsm** [comment]
I think it should be sufficient to just store the protocol scheme in the Request, not the whole uri. Everything else is broken down into HTTP terms (e.g. the auth headers), so it's just the schema that is missed I think.
