### ISSUE TITLE
Link module doesn't expose any functions

### ISSUE THREAD

**Issue by sgrove** [mirage/ocaml-cohttp#673]
Am I right that there are no exported functions in here to actually use any of the http link stuff? https://github.com/mirage/ocaml-cohttp/blob/master/cohttp/src/link.mli

e.g. There are all of these variants https://github.com/mirage/ocaml-cohttp/blob/master/cohttp/src/link.ml#L46 and rel_of_string, but none of it is used or exposed.

I was working on implementing some Link parsing stuff, and saw that a lot of work seems to have already been done, so was a bit surprised - is the design intentional, or would it be ok to expose more of the `Link` module?

**Comment by rgrinberg** [comment]
It should be ok to expose whatever you find useful.

**Comment by mseri** [comment]
Please reopen if needed
