### ISSUE TITLE
async ssl usage with 2.5.0 release

### ISSUE THREAD

**Issue by joprice** [mirage/ocaml-cohttp#687]
I tried upgrading to 2.5.0, because async_ssl is not released yet for 0.13.0. Since I can't resolve the dependency, I have to remove it, and then I get the following error: `(monitor.ml.Error (Failure "Ssl not available, recompile with Async_ssl")` Is there a workaround to use async with the current release or should I just sit tight until async_ssl is released?

**Comment by mseri** [comment]
Should no longer be a problem and will be definitevly solved in the next release
