### ISSUE TITLE
Document how to set timeouts on blocking requests

### ISSUE THREAD

**Issue by sahanakk** [mirage/ocaml-cohttp#691]
Given the below-mentioned code for client, how do we add a timeout. For eg . I want the request to timeout after 1 minute if the server doesn't respond.

    (* client_example.ml *)
    open Lwt
    open Cohttp
    open Cohttp_lwt_unix

    let body =
      Client.get (Uri.of_string "https://www.reddit.com/") >>= fun (resp, body) ->
      let code = resp |> Response.status |> Code.code_of_status in
      Printf.printf "Response code: %d\n" code;
      Printf.printf "Headers: %s\n" (resp |> Response.headers |> Header.to_string);
      body |> Cohttp_lwt.Body.to_string >|= fun body ->
      Printf.printf "Body of length: %d\n" (String.length body);
      body

    let () =
      let body = Lwt_main.run body in
          print_endline ("Received body\n" ^ body)

**Comment by CraigFe** [comment]
You can use [`Lwt.pick`](https://ocsigen.org/lwt/4.1.0/api/Lwt) to set a timeout on the execution of a thread:

```ocaml
let compute ~time ~f =
  Lwt.pick [
      (f () >|= fun v -> `Done v);
      (Lwt_unix.sleep time >|= fun () -> `Timeout);
    ]
```

In this case, you'd want to set a timeout on the `Client.get` thread.

**Comment by mseri** [comment]
I think we should put this in the docs or in a FAQ section somewhere

**Comment by CraigFe** [comment]
Good idea; I'll reopen the issue to track that.

**Comment by bikallem** [comment]
Is there a similar way to do that in async version?

**Comment by CraigFe** [comment]
> Is there a similar way to do that in async version?

You could do it directly using Async's [`with_timeout`](https://ocaml.janestreet.com/ocaml-core/latest/doc/async_unix/Async_unix/Clock/index.html#val-with_timeout).

**Comment by mseri** [comment]
Added to the README update
