### ISSUE TITLE
Managing Cookies Across Multiple Requests

### ISSUE THREAD

**Issue by smolck** [mirage/ocaml-cohttp#700]
I wasn't quite sure of a good title, so that may not be the most accurate description of what I'd like to do, but I think it gives a general idea of what I'm trying to accomplish.

[Using Haskell's wreq library](http://www.serpentine.com/wreq/tutorial.html#session), you can do this:
```haskell
{-# LANGUAGE OverloadedStrings #-}

import Control.Lens
import Network.Wreq
import qualified Network.Wreq.Session as S

main :: IO ()
main = S.withSession $ \sess -> do
  -- First request: tell the server to set a cookie
  S.get sess "http://httpbin.org/cookies/set?name=hi"

  -- Second request: the cookie should still be set afterwards.
  r <- S.post sess "http://httpbin.org/post" ["a" := (3 :: Int)]
  print $ r ^. responseCookie "name" . cookieValue
```
I think this is pretty self-explanatory; basically it allows me to make one request and then carry cookies set from that request on to the next request, and also access said cookies afterwards. I'm also able to [initialize a session with cookies using a `CookieJar`](https://hackage.haskell.org/package/wreq-0.5.3.2/docs/Network-Wreq-Session.html#v:newSessionControl).

The same sort of thing can be achieved in Python using the `requests` library (example from https://2.python-requests.org/en/master/user/advanced/#session-objects):
```python
s = requests.Session()

s.get('https://httpbin.org/cookies/set/sessioncookie/123456789')
r = s.get('https://httpbin.org/cookies')

print(r.text)
# '{"cookies": {"sessioncookie": "123456789"}}'
```
You can also update the cookies after creating a new session with `session.cookies.update(...)`, thus allowing for saving the cookies to be used in another session.

However, I'm unsure how to achieve the same sort of thing with this library. How might I go about implementing the same sort of functionality as in the examples above?

**Comment by mseri** [comment]
To manage sessions there is https://github.com/inhabitedtype/ocaml-session which is compatible with cohttp
