### ISSUE TITLE
Headers: missing function to set a header, possibly overwriting an existing header

### ISSUE THREAD

**Issue by vouillon** [mirage/ocaml-cohttp#701]
It would be convenient to have a function in module `Header` to add a header possibly replacing an existing header with the same key (similarly to `Hashtbl.replace`). The function `Header.replace` was doing just that, but its semantics was changed by #694

**Comment by mseri** [comment]
There is `Header.add` to add a header. We could add `replace_if_exists` and `add_or_replace` functions which I am more in favour of and deprecate `replace` (maybe also revert to the old `replace` behaviour but update its docstring).

Since the conduit 3 release will be breaking anyways, we can fix the API if needed.

**Comment by avsm** [comment]
I hadn't noticed that the `Headers.replace` changed in a minor release -- it was indeed a documentation error, but it would perhaps be better to keep its behaviour matching `Hashtbl.replace` (that is, add-or-update).

How about:

- `Header.replace` goes back to add-or-update with a corrected docstring
- Add `Header.update` which fails if the key doesn't exist.

We could cut this as a minor release (as it's restoring old functionality and adding a new function), and then merge conduit 3 for a 3.0 release subsequently to that.

**Comment by mseri** [comment]
> We could cut this as a minor release (as it's restoring old functionality and adding a new function), and then merge conduit 3 for a 3.0 release subsequently to that.

Yes, this is what I was planning to do. But I wasn't sure if it is worth to do a renaming for 3.0.

> How about:
>
>-    Header.replace goes back to add-or-update with a corrected docstring
>-   Add Header.update which fails if the key doesn't exist.

If we add `update`, then there is no need to change the API in the 3.0 version, which is even better!
You think it should fail (say with `Not_found`) if the key is not there instead of doing nothing?

**Comment by avsm** [comment]
I am a little reluctant to add more exception raising functions. But we could do `update` (return an option) and `update_exn` to raise a Not_found.

**Comment by pm-mck** [comment]
Maybe a bit late in the game, but could `update` work similarly to [Map.S.update](https://caml.inria.fr/pub/docs/manual-ocaml/libref/Map.S.html)?

For quick reference:
```
ocaml
val update : key -> ('a option -> 'a option) -> 'a t -> 'a t
```

> update x f m returns a map containing the same bindings as m, except for the binding of x. Depending on the value of y where y is f (find_opt x m), the binding of x is added, removed or updated. If y is None, the binding is removed if it exists; otherwise, if y is Some z then x is associated to z in the resulting map. If x was already bound in m to a value that is physically equal to z, m is returned unchanged (the result of the function is then physically equal to m).

> Since 4.06.0

**Comment by mseri** [comment]
That is fine with me, and it is possibly even better, so that the semantics remain close to Map. @hannesm @avsm @dinosaure what do you think?

**Comment by avsm** [comment]
the `Map.S.update` interface looks good to me @mseri! Thanks for the suggestion @pm-mck

**Comment by mseri** [comment]
The new update function will appear in the next release, along with the semantics fix
