### ISSUE TITLE
HTTP 308: Resume incomplete or Permanent redirect?

### ISSUE THREAD

**Issue by emillon** [mirage/ocaml-cohttp#710]
Hi,

Cohttp lists 308 as a code for "Resume Incomplete", but some hosts use it for "Permanent Redirect".
It seems that the earlier is nonstandard, but I'm not too sure.

References: [httpstatuses](https://httpstatuses.com/308), [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308), [RFC7538](https://tools.ietf.org/html/rfc7538)

**Comment by samoht** [comment]
This is generated from https://github.com/mirage/ocaml-cohttp/blob/master/cohttp/scripts/codes/3.json#L169-L185 (which comes from https://httpstatuses.com/)

**Comment by samoht** [comment]
I guess we just need to update the JSON file with the new spec :-)

**Comment by emillon** [comment]
That would break API, but I'm not sure how to handle that in a graceful way.

**Comment by mseri** [comment]
If we need to break the API, this is the time. With conduit 3.0, the next cohttp 3.0 will be a breaking release anyways

**Comment by emillon** [comment]
This website seems to have its sources at https://github.com/rmaake1/httpstatuses. There are no updates since 2016 but more importantly this does not use JSON files as sources. I found [a fork](https://github.com/arunshejul/httpstatus.es/tree/master/codes) with the JSON files and some updates, including for 308, but it's from 2014. I'll try to update this.
