### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by dinosaure** [mirage/ocaml-cohttp#727]
I think it's time to prepare a release of `cohttp` and propose a new version of it with `conduit.3.0.0` (released) (see #692). As far as I can tell, #686 is the only remaining PR which should be included into this release. A documentation pass was done to explain a bit the new API of `conduit.3.0.0` and, from some third-part libraries, it seems that we globally keep the same behavior.

However, the release includes some others works such as:
- Long-running connection (pipeline) (on `cohttp-async`)
- Fix leak of streams (on `cohttp-lwt`)
- Fix dead-lock on logs (on `cohttp-lwt`)
- Fix `Transfer-Encoding` ordering in headers
- Simplification of the `js_of_ocaml` support
- Fix encoding of empty bodies
- Fix empty chunk on pipe (on `cohttp-async`)
- Add the scheme of the given `Uri.t` into the request

And may be I missed some PRs. From the current `Changelog` it seems that all was properly reported (thanks to @mseri).

The new bump is a major release because we change a bit the layout of `cohttp` where 2 new packages appeared and the initial `cohttp-lwt-unix` uses `ocaml-tls` now:
- `cohttp-lwt-unix-nossl` is `cohttp` without SSL/TLS support
- `cohttp-lwt-unix-ssl` is `cohttp` with OpenSSL support
- and, as I said, `cohttp-lwt-unix` uses `ocaml-tls` now

Due to the fact that `cohttp` is widely used by several people, a feedback of this version is welcome from any users - but, again, as far as I can tell, you should have the same result as before. Only `conduit` users must update their codebase. The API did not really break (if you don't directly use `conduit`) so you should compile your code as is.

So the plan is to prepare the release and I will do a pass on issues to close some of them if they are related to `conduit` (and if the new release of `conduit` fix them).

If you have any troubles, please tell me on this issue and I can help you then. If you have any concerns about this release, please fill an issue to open a discussion and find a solution before the release. Due to the lockdown in France, I can spend more times on `cohttp`, thanks.

**Comment by hannesm** [comment]
This plan sounds good to me. I'm not sure whether #686 should be included or not, for sure a comparison of values (request / response / body / headers) would be appreciated.

**Comment by mseri** [comment]
The release will appear on the opam-repository after the tezos PR is closed or merged since we need to test which revdeps do need the upper bounds (most of the packages I use work fine with cohttp 3.0.0, I think pre-upperbounding everything is overkill).

The branch for the PR is ready here: https://github.com/mseri/opam-repository/tree/release-cohttp-3.0.0

**Comment by hannesm** [comment]
Thanks for the work, it would be great to have this PRed to opam-repository soonish :)

**Comment by mseri** [comment]
Until tezos pr is open there is no point in doing it unfortunately
