### ISSUE TITLE
Cohttp_lwt timeout issue

### ISSUE THREAD

**Issue by zeptometer** [mirage/ocaml-cohttp#731]
While investigating the cause of [an opam-publish issue](https://github.com/ocaml-opam/opam-publish/issues/113), I found that Cohttp_lwt throws a timeout error when it tries to connect any URL.

When I follow https://github.com/mirage/ocaml-cohttp#client-tutorial as-is, I got the following error.
```
$ dune exec ./client_example.exe
Fatal error: exception Unix.Unix_error(Unix.ETIMEDOUT, "connect", "")
```

I tried using `COHTTP_DEBUG=1`, but it didn't show any debug log.

My environment is
* Ubuntu 20.04 on WSL2
* OCaml 4.11.1
* cohttp, cohttp-lwt, cohttp-lwt-unix 2.5.4

WSL2 might be related to this issue, while I confirmed that `curl -i https://www.reddit.com/` in WSL2 bash returned a 200 response.

**Comment by dinosaure** [comment]
Currently, the bug is not reproducible with `trunk`, OCaml 4.10.0, Ubuntu 16.04. Currently, a release (`3.0.0`) is into the pipe, you should test with this new version (with `opam pin` or waiting the release) :+1:.

**Comment by zeptometer** [comment]
After upgrading to `3.0.0`, I no longer see the timeout issue. Thank you!
