### ISSUE TITLE
Invalid HTTP Status line when a custom status code is used

### ISSUE THREAD

**Issue by aalekseyev** [mirage/ocaml-cohttp#752]
In https://github.com/janestreet/cohttp_async_websocket/pull/1 a user reported that using  `` `Code 101 `` as a HTTP response status makes cohttp generate a response header that can't be parsed by Safari.

The response status line generated is `HTTP/1.1 101`, which, I would argue, is not compliant with the [spec](https://tools.ietf.org/html/rfc7230#section-3.1.2) because it doesn't have the second space character.

The culprit seems to be this line:
https://github.com/mirage/ocaml-cohttp/blob/c3a59cd11fae2ccf084fbfc3eb02b75773511d25/cohttp/scripts/generate.ml#L241

Maybe it should be changed to generate `HTTP/1.1 101 `, instead (note the extra space)?
Or, less confusingly, `HTTP/1.1 101 Status 101`?

**Comment by mseri** [comment]
I am surprised about this. I had implemented your fix, but I think the issue must be somewhere else. Are you using the latest version of cohttp?

Right now, if I try it locally, I get that https://github.com/mirage/ocaml-cohttp/blob/c3a59cd11fae2ccf084fbfc3eb02b75773511d25/cohttp/src/response.ml#L110 contains the correct string:
```ocaml
# Cohttp.Code.(string_of_status @@ status_of_code 101)
;;
- : string = "101 Switching Protocols"
```

**Comment by mseri** [comment]
Oh sorry, I should not do this at night. I see, the issue is that they were using the "handwritten" `` `Code 101 ``. I will have a look asap, but when I am less sleepy.

**Comment by aalekseyev** [comment]
Thank you, the fix looks good to me!
