### ISSUE TITLE
[feature wish] High-level function for performing a GET that follows redirects

### ISSUE THREAD

**Issue by protz** [mirage/ocaml-cohttp#76]
There's a whole bunch of ways to perform redirections: 301, other 3xx HTTP codes (temporarily moved, etc.), `Location:` header, etc. etc.. I kind of wish for an extra "follow_redirects" parameter for the Cohttp_lwt_unix.Client.get function, that doesn't require me to do that myself. Curl has that, and it's bloody convenient :-).

Cheers,

~ jonathan

**Comment by trevorsummerssmith** [comment]
I am building client redirect-following functionality for my aws client and would like to get it upstreamed once it is in a ready state. Is there any more discussion or design thoughts about a redirect-following client? If not, can I create some gists once I am ready and get discussion going? Thanks! @rgrinberg

**Comment by avsm** [comment]
See https://GitHub.com/avsm/opam-mirror for code that does this -- needs to be pulled out into an ocurl lib

**Comment by rgrinberg** [comment]
@trevorsummerssmith would be great to have this. Let me know if you need anything from me.

I do think we have to refactor the client to be a little more friendly to such added functionality. E.g. a client should be able to generate get/post/put/delete/etc. just by providing his own call function. @avsm what do you think?

**Comment by trevorsummerssmith** [comment]
@rgrinberg Thanks! I have a bunch of thoughts on this. I need to write some more code before they will be more together. I'm aiming to have something ready to talk about early next week.

**Comment by rgrinberg** [comment]
-1 On this in retrospect. I'd much rather cohttp focus on getting the low level layer right and allow for people to implement this on their own.

**Comment by 1hko** [comment]
Just to illustrate @rgrinberg's point...

I was writing a simple `Client.t` for accessing a remote using basic auth. The remote sometimes responds with redirects and the client below is capable of following them. I wrote the cases that cover my needs but there's countless status codes that just fall through and could raise an `UnhandledStatus` exception if used on endpoints that return other statuses. It only supports `GET` requests, which again is all my project needed.

This is quite a bit of wiring but it was an enlightening experience for me. I now realize how difficult it would be to write something that handles all cases automatically while maintaining grace

The code here is part of my first project in Ocaml. I'm new to the language so I'm interested to see how other people solve this using cohttp

**client.ml**

```ocaml
open Core
open Async

exception TooManyRedirects [@@deriving sexp]
exception UnhandledStatus of Cohttp.Code.status_code [@@deriving sexp]

type t =
  string
[@@deriving sexp]

let make user pass =
  let cred = `Basic (user, pass) in
  Cohttp.Auth.string_of_credential cred

let rec get ?interrupt ?(max_redirects = 5) t uri =
  let headers = Cohttp.Header.of_list [ "authorization", t ] in
  let req = Cohttp.Request.make_for_client ~headers `GET uri in
  Cohttp_async.Client.request ?interrupt ~uri req
  >>= fun (res, body) ->
  return (req, res, body) (* my program needs access to each of these data members *)
  >>= follow_redirect t max_redirects

and follow_redirect t max_redirects (req, res, body) =
  if max_redirects = 0 then
    raise TooManyRedirects
  else
    let status = Cohttp.Response.status res in
    match status with
    | `OK -> return (req, res, body)
    | `Found 
    | `Moved_permanently
    | `Temporary_redirect -> (* wide variety of cases to handle *)
      handle_redirect t (req, res, body)
      >>= follow_redirect t (max_redirects - 1)
    | _ as s -> raise (UnhandledStatus s) (* many unhandled cases *)

and handle_redirect t (req, res, body) =
  let headers = Cohttp.Response.headers res in
  let location = Cohttp.Header.get headers "location" in
  match location with
  | None -> return (req, res, body) (* redirect without location header could signal an error *)
  | Some url -> get t (Uri.of_string url)

```

**Comment by brendanlong** [comment]
I started working on a higher-level Cohttp-based client in https://github.com/brendanlong/blue-http which handles this (among other things).

The [redirect logic is relatively simple if anyone wants to steal it](https://github.com/brendanlong/blue-http/blob/master/src/redirect.ml), and then you can wrap any Cohttp_async.Client function with [`Redirect.with_redirects ?max_redirects uri (fun uri -> ...)`](https://github.com/brendanlong/blue-http/blob/master/src/blue_http.ml#L38)

**Comment by hcarty** [comment]
@brendanlong Maybe we can collaborate a bit? I have ezrest which seems like it's pretty similar - https://github.com/hcarty/ezrest

I've been using ezrest for years but haven't gotten around to making a formal release.

**Comment by brendanlong** [comment]
Yeah I'd like to make a thing that usable for multiple people. I'm not sure how quickly I can get to it though. My version currently only supports Async and yours uses Lwt. I think the next step for me is breaking out [the connection pool](https://github.com/brendanlong/blue-http/blob/master/src/pool.ml) and making it work with both Async and Lwt. I'm just incredibly busy so I don't know if I can realistically collaborate at a useful speed :\

**Comment by mseri** [comment]
I have added examples on how to handle redirects in the README, created a ticked to add it to the documentation, and pointed at this issue. I am going to close it for now.
