### ISSUE TITLE
Cohttp_lwt_unix timeout on wsl2

### ISSUE THREAD

**Issue by elboza** [mirage/ocaml-cohttp#852]
ENVIRONMENT: archlinux on wsl2

DESCRIPTION:
ocaml-cohhtp is timing out on wsl2. 

STEPS to REPRODUCE:
- try the example 'client tutorial' in the README file  https://github.com/mirage/ocaml-cohttp#client-tutorial 

ACTUAL RESULT:
Fatal error: exception Unix.Unix_error(Unix.ETIMEDOUT, "connect", "")

EXPECTED RESULT:
http connecton working

**Comment by elboza** [comment]
ok. solvewd by adjusting dsn in wsl2. Not related to cohttp.
closing issue.

**Comment by mseri** [comment]
Thanks. And sorry for the slowliness, I was waiting to get my hands on a windows machine to test it
