### ISSUE TITLE
HTTP package

### ISSUE THREAD

**Issue by anmonteiro** [mirage/ocaml-cohttp#856]
Love the idea of the new upcoming `http` package. It has types that we could share across HTTP implementations in the OCaml ecosystem.

How feasible would it be to pull the parser parts out of this package though, and have it contain mostly types?

**Comment by rgrinberg** [comment]
What would be the advantage? The parser is not part of the public interface and requires no additional dependencies. The only gain would be to shave off the object size of binaries by a little bit. Is that worth it?

**Comment by anmonteiro** [comment]
> The only gain would be to shave off the size of binaries by a little bit. Is that worth it?

That was the rationale behind my suggestion.

**Comment by rgrinberg** [comment]
Alright, feel free to send a PR that moves the parser into a separate library (within the same package) if you really need this.

**Comment by anmonteiro** [comment]
I don't "really need this". I think the benefit here would be the ability to share those type representations across the ecosystem. If this is not as welcome as I anticipated, I'm OK sticking with the status quo.

**Comment by rgrinberg** [comment]
> I think the benefit here would be the ability to share those type representations across the ecosystem

Is this benefit not already realized?

> If this is not as welcome as I anticipated, I'm OK sticking with the status quo.

It's not that it's not welcome, it's just a bit too much of a niche feature for me to invest time in.

**Comment by anmonteiro** [comment]
> Is this benefit not already realized?

I'd imagine an HTTP library that's going to implement its own parser not to need to bring in another one.

>  it's just a bit too much of a niche feature for me to invest time in.

This makes sense. I'll see if I can spend some of my own time on this soon.

**Comment by rgrinberg** [comment]
Sure there's a bit of redundancy but I claim that it's mostly harmless. OCaml binaries aren't very nimble after all.

By the way, give our http parser a try. It's hand written and is faster than httpaf's.

**Comment by craff** [comment]
With cohttp-eio, http is almost enough ... except for Cohttp.Path.resolve_local_file.
It would be nice if Http had this.

**Comment by rgrinberg** [comment]
Closing as no one else cares about shrinking the binary size of `http`
