### ISSUE TITLE
Redirect example on README.md doesn't compile

### ISSUE THREAD

**Issue by mro** [mirage/ocaml-cohttp#911]
Hi @mseri,

when I try to compile <https://github.com/mirage/ocaml-cohttp#dealing-with-redirects> after I add the `Logs` package dependency, I get a

```sh
File "lib/http.ml", lines 52-55, characters 10-20:
52 | ..........Logs.warn (fun m ->
53 |               m "Permanent redirection from %s to %s"
54 |                 (Uri.to_string request_uri)
55 |                 url)
Error: This expression has type unit but an expression was expected of type
         'a Lwt.t
make: *** [build] Error 1
```

Maybe the `Logs.warn` should be nested in a `Lwt.return`?

**Comment by mseri** [comment]
You are right, either that or one needs thanks for reporting it.
