### ISSUE TITLE
Error building with js of ocaml using cohttp-lwt-jsoo

### ISSUE THREAD

**Issue by papsonic** [mirage/ocaml-cohttp#924]
I am having missing primitives building with js of ocaml only using cohttp-lwt-jsoo function.

Here is the code :

```
let () =
  Cohttp_lwt_jsoo.Client.get @@ Uri.of_string "https://v2.ocaml.org/manual/index.html" |> ignore
```

The libraries in my `dune` file : `js_of_ocaml-lwt cohttp-lwt-jsoo`

But it returns, when building :
```
There are some missing primitives
Dummy implementations (raising 'Failure' exception) will be used if they are not available at runtime.
You can prevent the generation of dummy implementations with the commandline option '--disable genprim'
Missing primitives:
  bigstringaf_blit_from_bytes
  bigstringaf_blit_to_bytes
```

Any ideas ?

**Comment by mseri** [comment]
That is surprising, since this is used to work fine and, in fact, I cannot reproduce the error. The dependency chain should be that `uri` depends on `angstrom` which brings in `bigstringaf`, but this has been the situation for a few years already (since version 4.0.0) and `bigstringaf` has provided the js runtime since its first version: https://github.com/inhabitedtype/bigstringaf/blob/master/lib/runtime.js

I am doing the following:
```bash
$ cat dune
(executable
 (name jsoo)
 (modes js)
 (libraries cohttp-lwt-jsoo uri))
$ cat dune-project
(lang dune 3.4)
(name jsoo)
$ cat jsoo.ml
let () =
  Cohttp_lwt_jsoo.Client.get @@ Uri.of_string "https://v2.ocaml.org/manual/index.html" |> ignore
$ cat test.html
  <!DOCTYPE html>
<html>
  <head>
    <script src="./_build/default/jsoo.bc.js">
    </script>
  </head>
  <body>
  </body>
</html>
```

Then
```
$ dune build ./jsoo.bc.js
$ open test.html
```
and look at the js console output

**Comment by papsonic** [comment]
Thank you very much for your answer.

I am indeed not having this issue using `modes js`.
What is was using back then was :

```
(executable
 (modes byte)
 (name jsoo)
 (preprocess
  (pps lwt_ppx js_of_ocaml-ppx))
 (libraries uri cohttp-lwt-jsoo))

(rule
(targets jsoo.js)
(action
 (run
  %{bin:js_of_ocaml}
  --source-map
  %{dep:jsoo.bc}
  -o
  %{targets}
  --pretty)))

(alias
(name default)
(deps
 jsoo.js
 index.html
 (glob_files static/*)))
```

**Comment by papsonic** [comment]
Is this still a weird behavior ? I don't know if I should close this issue then.

**Comment by mseri** [comment]
I think if you don't use mode js, node will link the c library and that is where it fails. But I don't know. Maybe try to ask on the dune repo or the dune discord channel to check what is the difference between your invocation an mine

**Comment by papsonic** [comment]
Ok ill check, thank you.
