### ISSUE TITLE
cohttp_curl: First HTTP header is prepended to output

### ISSUE THREAD

**Issue by ScoreUnder** [mirage/ocaml-cohttp#987]
Example:

```ocaml
let testfun () =
  let url = "https://httpbin.org/status/200" in
  let headers = [ ("Test-header", "this should not appear in output"); ("Content-Type", "application/json") ] in
  let body = "[\"post body\"]" in
  let request =
    Cohttp_curl_lwt.Request.create
      ~headers:(Http.Header.of_list headers)
      `POST ~uri:url
      ~input:(Cohttp_curl_lwt.Source.string body)
      ~output:Cohttp_curl_lwt.Sink.string
  in
  let context = Cohttp_curl_lwt.Context.create () in
  let cohttp_response = Cohttp_curl_lwt.submit context request in
  let response_body = Cohttp_curl_lwt.Response.body cohttp_response in
  let open Lwt.Syntax in
  let+ response_body = response_body in
  print_endline response_body

let () =
  Lwt_main.run (testfun ())
```

The code here should just return the empty body that the URL usually gives, but instead it gives the first header. Similarly, `https://httpbin.org/post` is supposed to give you valid JSON, but here the header is prepended so it doesn't.

A glance at the code in `cohttp_curl.ml` shows that a Buffer called `buf` is created and shared between both the header formatting step and the output reading step:
https://github.com/mirage/ocaml-cohttp/blob/b7182a17e9769c7d08c5b05e2512e0eca605f74e/cohttp-curl/src/cohttp_curl.ml#L56-L126

However the buffer is not cleared between these two steps, meaning whichever header it processed last is still in the buffer before it starts getting data from curl.

**Comment by rgrinberg** [comment]
Do you want to send a PR? Using two different buffers should be enough.
